<?php 

use \Illuminate\Database\Seeder;
use Victorem\Entities\Location;

class LocationsMetaTableSeeder extends Seeder
{
    public static $municipalities = [
        'acacías',
        'barranca de upía',
        'cabuyaro',
        'castilla la nueva',
        'cubarral',
        'cumaral',
        'el calvario',
        'el castillo',
        'el dorado',
        'fuente de oro', // 20
        'granada',
        'guamal',
        'la macarena',
        'la uribe',
        'lejanías',
        'mapiripán',
        'mesetas',
        'puerto concordia',
        'puerto gaitán',
        'puerto lleras',
        'puerto lópez',
        'puerto rico',
        'restrepo',
        'san carlos de guaroa',
        'san juan de arama',
        'san juanito',
        'san martín',
        'vista hermosa'
    ];

    public static $neighborhoods = [
        ['name' => 'antonio ricaute',  'superior' => 5],
        ['name' => 'brisas del guatiquia',    'superior' => 5],
        ['name' => 'las delicias',    'superior' => 5],
        ['name' => 'el porvenir', 'superior' => 5],
        ['name' => 'san gregorio',    'superior' => 5],
        ['name' => 'san isidro',  'superior' => 5],
        ['name' => 'santafe', 'superior' => 5],
        ['name' => 'santa ines',  'superior' => 5],
        ['name' => 'la vainilla', 'superior' => 5],
        ['name' => '20 de julio', 'superior' => 5],
        ['name' => 'villa  julia',    'superior' => 5],
        ['name' => 'portales del llano',  'superior' => 10],
        ['name' => 'villa del rio uno',   'superior' => 10],
        ['name' => 'montecarlo',  'superior' => 10],
        ['name' => 'ciudad porfia sector cuatro', 'superior' => 10],
        ['name' => 'playa rica',  'superior' => 10],
        ['name' => 'alamos sur montecarlo',   'superior' => 10],
        ['name' => 'catumare',    'superior' => 10],
        ['name' => 'ciudad jardin sector ciudadela cofrem',   'superior' => 10],
        ['name' => 'altos de guatape - guatape dos',  'superior' => 10],
        ['name' => 'villa marina',    'superior' => 10],
        ['name' => 'villa lorena',    'superior' => 10],
        ['name' => 'villa juliana',   'superior' => 10],
        ['name' => 'villa del rio dos',   'superior' => 10],
        ['name' => 'maria paz',   'superior' => 10],
        ['name' => 'villa sonia', 'superior' => 10],
        ['name' => 'las americas',    'superior' => 10],
        ['name' => 'villa milena',    'superior' => 10],
        ['name' => 'el divino niño',  'superior' => 10],
        ['name' => 'la rochela',  'superior' => 10],
        ['name' => 'san jorge cuarta etapa',  'superior' => 10],
        ['name' => 'el darien',   'superior' => 10],
        ['name' => 'nuevo amanecer',  'superior' => 10],
        ['name' => 'maranatha',   'superior' => 10],
        ['name' => 'los heroes',  'superior' => 10],
        ['name' => 'villas del ocoa', 'superior' => 10],
        ['name' => 'montecarlo sector tres',  'superior' => 10],
        ['name' => 'santa librada',   'superior' => 10],
        ['name' => 'caminos de montecarlo',   'superior' => 10],
        ['name' => 'ciudadela brasilia',  'superior' => 10],
        ['name' => 'ciudad porfia sector uno',    'superior' => 10],
        ['name' => 'porfia sector tres',  'superior' => 10],
        ['name' => 'villa samper',    'superior' => 10],
        ['name' => 'santa cecilia',   'superior' => 10],
        ['name' => 'bifamiliares  ariguani tres', 'superior' => 7],
        ['name' => 'gaviotas',    'superior' => 7],
        ['name' => 'villa alejandra', 'superior' => 7],
        ['name' => 'bochica uno', 'superior' => 7],
        ['name' => 'villa helena',    'superior' => 7],
        ['name' => 'menegua', 'superior' => 7],
        ['name' => 'villa ortiz i etapa', 'superior' => 7],
        ['name' => 'el estero',   'superior' => 7],
        ['name' => 'cataluña',    'superior' => 7],
        ['name' => 'cavivir', 'superior' => 7],
        ['name' => 'estero alto', 'superior' => 7],
        ['name' => 'barzal  bajo',    'superior' => 4],
        ['name' => 'las camelias',    'superior' => 7],
        ['name' => 'guadalajara', 'superior' => 7],
        ['name' => 'hacaritama dos y tres',   'superior' => 7],
        ['name' => 'villa del sol',   'superior' => 2],
        ['name' => 'hacaritama uno y cuatro', 'superior' => 7],
        ['name' => 'nueva floresta',  'superior' => 7],
        ['name' => 'la concepcion',   'superior' => 2],
        ['name' => 'la primavera',    'superior' => 2],
        ['name' => 'el danubio',  'superior' => 7],
        ['name' => 'macunaima cuatro',    'superior' => 7],
        ['name' => 'villa ortiz dos', 'superior' => 7],
        ['name' => 'acapulco',    'superior' => 7],
        ['name' => 'el remanso',  'superior' => 7],
        ['name' => 'bello horizonte', 'superior' => 7],
        ['name' => 'ay mi llanura',   'superior' => 7],
        ['name' => 'villa melida',    'superior' => 7],
        ['name' => 'popular', 'superior' => 7],
        ['name' => 'valles de la carolina',   'superior' => 7],
        ['name' => 'el paraiso',  'superior' => 6],
        ['name' => 'urabanizacion la carolina',   'superior' => 7],
        ['name' => 'kirpas',  'superior' => 7],
        ['name' => 'prados de siberia',   'superior' => 6],
        ['name' => 'villa johana dos',    'superior' => 2],
        ['name' => 'alamos santa rosa',   'superior' => 10],
        ['name' => 'ariguani',    'superior' => 7],
        ['name' => 'el recreo tres',  'superior' => 6],
        ['name' => 'el recreo',   'superior' => 6],
        ['name' => 'nueva colombia uno',  'superior' => 2],
        ['name' => 'nueva colombia dos',  'superior' => 2],
        ['name' => 'morichal',    'superior' => 6],
        ['name' => 'las malvinas',    'superior' => 2],
        ['name' => 'el milagro rosales',  'superior' => 6],
        ['name' => 'madrigal uno',    'superior' => 6],
        ['name' => 'el jordan',   'superior' => 6],
        ['name' => 'vencedores',  'superior' => 2],
        ['name' => 'hierbabuena', 'superior' => 6],
        ['name' => 'villa suarez',    'superior' => 6],
        ['name' => 'santa helena ',   'superior' => 6],
        ['name' => 'santa helena sector dos', 'superior' => 6],
        ['name' => 'san felipe',  'superior' => 6],
        ['name' => 'los rosales', 'superior' => 6],
        ['name' => 'vda caños negros sec  1 la reliquia', 'superior' => 7],
        ['name' => 'la florencia',    'superior' => 6],
        ['name' => 'la desmotadora',  'superior' => 6],
        ['name' => 'el delirio',  'superior' => 5],
        ['name' => 'cedritos',    'superior' => 6],
        ['name' => 'calamar', 'superior' => 6],
        ['name' => 'villa johana uno',    'superior' => 2],
        ['name' => 'castilla',    'superior' => 6],
        ['name' => 'el bambu',    'superior' => 6],
        ['name' => 'alcala',  'superior' => 6],
        ['name' => 'antonio villavicencio',   'superior' => 6],
        ['name' => 'catumare sector dos', 'superior' => 10],
        ['name' => 'vda las mercedes sector la union',    'superior' => 2],
        ['name' => 'san ignacio uno y dos',   'superior' => 2],
        ['name' => 'portales de nuevo horizonte', 'superior' => 10],
        ['name' => 'la isla sector playa rica',   'superior' => 10],
        ['name' => 'villa nieves',    'superior' => 2],
        ['name' => 'santander',   'superior' => 5],
        ['name' => 'el emporio',  'superior' => 3],
        ['name' => 'san marcos',  'superior' => 8],
        ['name' => 'la victoria', 'superior' => 3],
        ['name' => 'nueva granada',   'superior' => 3],
        ['name' => 'panorama',    'superior' => 3],
        ['name' => 'rondinela',   'superior' => 3],
        ['name' => 'santa josefa militar',    'superior' => 3],
        ['name' => 'el rosal',    'superior' => 3],
        ['name' => 'chapinerito alto',    'superior' => 3],
        ['name' => 'el recuerdo', 'superior' => 3],
        ['name' => 'jose antonio galan',  'superior' => 2],
        ['name' => 'el triunfo',  'superior' => 3],
        ['name' => 'siete de agosto', 'superior' => 4],
        ['name' => 'brisas de la esperanza',  'superior' => 9],
        ['name' => 'comuneros',   'superior' => 9],
        ['name' => 'siete de agosto bajo',    'superior' => 4],
        ['name' => 'cooperativo', 'superior' => 9],
        ['name' => 'san jose ',   'superior' => 4],
        ['name' => 'la salle',    'superior' => 4],
        ['name' => 'centauro',    'superior' => 9],
        ['name' => 'camilo torres',   'superior' => 4],
        ['name' => 'la coralina', 'superior' => 9],
        ['name' => 'los libertadores',    'superior' => 4],
        ['name' => 'esperanza sexta etapa',   'superior' => 9],
        ['name' => 'esperanza septima etapa', 'superior' => 9],
        ['name' => 'villas del buque',    'superior' => 2],
        ['name' => 'buque',   'superior' => 4],
        ['name' => 'el jardin',   'superior' => 9],
        ['name' => 'la  azotea',  'superior' => 4],
        ['name' => 'juan pablo segundo',  'superior' => 9],
        ['name' => 'multifamiliares la esperanza octava etapa',   'superior' => 9],
        ['name' => 'el palmar',   'superior' => 9],
        ['name' => 'rosa blanca oriental',    'superior' => 9],
        ['name' => 'san fernando',    'superior' => 4],
        ['name' => 'venecia', 'superior' => 6],
        ['name' => 'la alborada', 'superior' => 9],
        ['name' => 'las colinas', 'superior' => 4],
        ['name' => 'canaima', 'superior' => 8],
        ['name' => 'vda el cocuy',    'superior' => 2],
        ['name' => 'vda caños negros',    'superior' => 2],
        ['name' => 'el embudo',   'superior' => 8],
        ['name' => 'la florida',  'superior' => 8],
        ['name' => 'garcia bohorquez',    'superior' => 8],
        ['name' => 'vda barcelona',   'superior' => 2],
        ['name' => 'vda apiay',   'superior' => 2],
        ['name' => 'san cristobal',   'superior' => 2],
        ['name' => 'vda vegas del guayuriba', 'superior' => 2],
        ['name' => 'macarena',    'superior' => 8],
        ['name' => 'vda santa rosa de rio negro', 'superior' => 2],
        ['name' => 'guatiquia',   'superior' => 8],
        ['name' => 'vda el guamo',    'superior' => 2],
        ['name' => 'llano lindo', 'superior' => 2],
        ['name' => 'simon bolivar',   'superior' => 8],
        ['name' => 'san benito',  'superior' => 8],
        ['name' => 'vda el amor sector villahermosa', 'superior' => 2],
        ['name' => 'nuevo ricaute',   'superior' => 8],
        ['name' => 'vda alto de  pompeya',    'superior' => 2],
        ['name' => 'vda arrayanes',   'superior' => 2],
        ['name' => 'vda peralonso',   'superior' => 2],
        ['name' => 'vda la llanerita',    'superior' => 2],
        ['name' => 'vda san luis de ocoa',    'superior' => 2],
        ['name' => 'vda rio negrito', 'superior' => 2],
        ['name' => 'vda la vigia',    'superior' => 2],
        ['name' => 'santa marta', 'superior' => 9],
        ['name' => 'vda reforma la libertad', 'superior' => 2],
        ['name' => 'multifamiliar santa catalina',    'superior' => 2],
        ['name' => 'vda quebrada honda',  'superior' => 2],
        ['name' => 'vda san jose alto',   'superior' => 2],
        ['name' => 'vda san juan de ocoa',    'superior' => 2],
        ['name' => 'vda pipiral', 'superior' => 2],
        ['name' => 'vda el carmen',   'superior' => 2],
        ['name' => 'vda contadero',   'superior' => 2],
        ['name' => 'vda servita', 'superior' => 2],
        ['name' => 'vda santa maria baja',    'superior' => 2],
        ['name' => 'inspeccion puerto colombia',  'superior' => 2],
        ['name' => 'vda buena vista', 'superior' => 2],
        ['name' => 'vda san marcos de chafurray', 'superior' => 2],
        ['name' => 'villa bolivar',   'superior' => 9],
        ['name' => 'esperanza uno ',  'superior' => 9],
        ['name' => 'esperanza dos',   'superior' => 9],
        ['name' => 'la rosita primera y segunda etapa',   'superior' => 9],
        ['name' => 'parcelas brisas del ocoa',    'superior' => 2],
        ['name' => 'vda la poyata',   'superior' => 2],
        ['name' => 'hachon bella suiza',  'superior' => 2],
        ['name' => 'verdea puerto tembleque', 'superior' => 2],
        ['name' => 'villa patricia',  'superior' => 2],
        ['name' => 'el progreso', 'superior' => 6],
        ['name' => 'la pradera',  'superior' => 2],
        ['name' => 'vda la cecilia',  'superior' => 2],
        ['name' => 'doce de octubre', 'superior' => 3],
        ['name' => 'guatape', 'superior' => 10],
        ['name' => 'rincon de pompeya',   'superior' => 2],
        ['name' => 'el retiro',   'superior' => 8],
        ['name' => 'el refugio',  'superior' => 10],
        ['name' => 'san jorge',   'superior' => 10],
        ['name' => 'barzal alto sur', 'superior' => 4],
        ['name' => 'vda el amor sector primero de mayo',  'superior' => 2],
        ['name' => 'cantarrana ', 'superior' => 8],
        ['name' => 'la grama',    'superior' => 3],
        ['name' => 'nuevo horizonte', 'superior' => 10],
        ['name' => 'saman de la rivera',  'superior' => 2],
        ['name' => 'vda la concepción baja',  'superior' => 2],
        ['name' => 'vizcaya', 'superior' => 7],
        ['name' => 'vda vanguardia alta', 'superior' => 2],
        ['name' => 'vda santa helena baja',   'superior' => 2],
        ['name' => 'vda santa helena',    'superior' => 2],
        ['name' => 'vda san cristobal',   'superior' => 2],
        ['name' => 'el topacio',  'superior' => 2],
        ['name' => 'villa maria', 'superior' => 4],
        ['name' => 'centro',  'superior' => 4],
        ['name' => 'la ceiba',    'superior' => 6],
        ['name' => 'madrigal dos',    'superior' => 6],
        ['name' => 'manantial',   'superior' => 6],
        ['name' => 'subnormal los guaduales', 'superior' => 2],
        ['name' => 'triunfadores del ocoa',   'superior' => 2],
        ['name' => 'vda cairo medio', 'superior' => 2],
        ['name' => 'mesetas bajas sector dos',    'superior' => 4],
        ['name' => 'vda santa helena baja sector dos',    'superior' => 2],
        ['name' => 'vda vanguardia baja', 'superior' => 2],
        ['name' => 'vda palo marcado',    'superior' => 2],
        ['name' => 'carulu',  'superior' => 9],
        ['name' => 'villa humberto',  'superior' => 9],
        ['name' => 'teusaquillo', 'superior' => 9],
        ['name' => 'la bastilla', 'superior' => 6],
        ['name' => 'rosa blanca', 'superior' => 9],
        ['name' => 'sexta etapa b esperanza sec brisas del buque',    'superior' => 2],
        ['name' => 'vda el amor', 'superior' => 2],
        ['name' => 'vda quenane', 'superior' => 2],
        ['name' => 'vda palmichal',   'superior' => 2],
        ['name' => 'villa del oriente',   'superior' => 10],
        ['name' => 'cantarrana cuatro',   'superior' => 8],
        ['name' => 'bosques de rosa blanca',  'superior' => 9],
        ['name' => 'vda san isidro alto de la cumbre',    'superior' => 2],
        ['name' => 'ciudadela san antonio',   'superior' => 7],
        ['name' => 'chapinerito bajo',    'superior' => 3],
        ['name' => 'villas del alcaravan',    'superior' => 2],
        ['name' => 'la reliquia sector tres', 'superior' => 7],
        ['name' => 'cantarrana dos',  'superior' => 8],
        ['name' => 'la reliquia sector dos',  'superior' => 7],
        ['name' => 'la reliquia sector cuatro',   'superior' => 7],
        ['name' => 'remansos de rosa blanca', 'superior' => 9],
        ['name' => 'marsella',    'superior' => 8],
        ['name' => 'vda indostan',    'superior' => 2],
        ['name' => 'loma linda',  'superior' => 2],
        ['name' => 'la pradera',  'superior' => 2],
        ['name' => 'bosques de abajam',   'superior' => 6],
        ['name' => 'leon trece',  'superior' => 9],
        ['name' => 'industrial',  'superior' => 5],
        ['name' => 'jorge eliecer gaitan',    'superior' => 2],
        ['name' => 'marco antonio pinilla',   'superior' => 7],
        ['name' => 'villa encanto',   'superior' => 6],
        ['name' => 'villa fabiola',   'superior' => 6],
        ['name' => 'el rodeo',    'superior' => 6],
        ['name' => 'san carlos',  'superior' => 2],
        ['name' => 'viña del mar',    'superior' => 2],
        ['name' => 'catatumbo',   'superior' => 8],
        ['name' => 'ciudadela divino niño',   'superior' => 7],
        ['name' => 'la serrania', 'superior' => 9],
        ['name' => 'san jorge quinta etapa',  'superior' => 2],
        ['name' => 'vda la union',    'superior' => 2],
        ['name' => 'vda la union sector naturalia',   'superior' => 2],
        ['name' => 'vda montecarlo',  'superior' => 2],
        ['name' => 'vda buenos aires bajo',   'superior' => 2],
        ['name' => 'vda samaria', 'superior' => 2],
        ['name' => 'vda la argentina',    'superior' => 2],
        ['name' => 'vda santa maria alta',    'superior' => 2],
        ['name' => 'vda cairo bajo',  'superior' => 2],
        ['name' => 'vda lourdes', 'superior' => 2],
        ['name' => 'vda puente abadia',   'superior' => 2],
        ['name' => 'vda santa teresa',    'superior' => 2],
        ['name' => 'vda juan bosco caños negros', 'superior' => 2],
        ['name' => 'brisas del buque alto',   'superior' => 4],
        ['name' => 'rincon de las margaritas',    'superior' => 4],
        ['name' => 'la sabana',   'superior' => 2],
        ['name' => 'los cambulos',    'superior' => 3],
        ['name' => 'amaral',  'superior' => 8],
        ['name' => 'nueva jerusalem', 'superior' => 2],
        ['name' => 'villas del palmar',   'superior' => 9],
        ['name' => 'la isla', 'superior' => 4],
        ['name' => 'el caudal',   'superior' => 3],
        ['name' => 'vda cairo alto',  'superior' => 2],
        ['name' => 'vizcaya seis',    'superior' => 7],
        ['name' => 'la vega', 'superior' => 9],
        ['name' => 'ciudad salitre',  'superior' => 6],
        ['name' => 'sosiego', 'superior' => 2],
        ['name' => 'el consuelo', 'superior' => 2],
        ['name' => 'fikus',   'superior' => 7],
        ['name' => 'los maracos', 'superior' => 7],
        ['name' => 'trapiche',    'superior' => 4],
        ['name' => 'las ferias',  'superior' => 5],
        ['name' => 'san luis',    'superior' => 6],
        ['name' => 'olimpico',    'superior' => 7],
        ['name' => 'dos mil', 'superior' => 7],
        ['name' => 'gaitan',  'superior' => 5],
        ['name' => 'la lambada',  'superior' => 5],
        ['name' => 'villa carola',    'superior' => 10],
        ['name' => 'ariguanery',  'superior' => 10],
        ['name' => 'villa ortiz', 'superior' => 7],
        ['name' => 'macunaima',   'superior' => 7],
        ['name' => 'hacaritama',  'superior' => 7],
        ['name' => 'aguas claras',    'superior' => 7],
        ['name' => 'doña luz',    'superior' => 7],
        ['name' => 'buenos aires',    'superior' => 7],
        ['name' => 'seis de abril',   'superior' => 6],
        ['name' => 'el prado',    'superior' => 3],
        ['name' => 'covisan', 'superior' => 6],
        ['name' => 'cedral',  'superior' => 6],
        ['name' => 'los cerezos', 'superior' => 3],
        ['name' => 'la campiña',  'superior' => 3],
        ['name' => 'catalana',    'superior' => 3],
        ['name' => 'el poblado',  'superior' => 3],
        ['name' => 'manaure', 'superior' => 3],
        ['name' => 'virrey',  'superior' => 3],
        ['name' => 'nueva andalucia', 'superior' => 4],
        ['name' => 'villa julia', 'superior' => 5],
        ['name' => 'maizaro', 'superior' => 4],
        ['name' => 'villaflores', 'superior' => 4],
        ['name' => 'villacentro', 'superior' => 4],
        ['name' => 'camoa',   'superior' => 4],
        ['name' => 'balata',  'superior' => 4],
        ['name' => 'los pinos',   'superior' => 4],
        ['name' => 'bonanza', 'superior' => 4],
        ['name' => 'villa codem', 'superior' => 4],
        ['name' => 'balcones de toledo',  'superior' => 4],
        ['name' => 'sansouci',    'superior' => 4],
        ['name' => 'galan',   'superior' => 4],
        ['name' => 'pontevedra',  'superior' => 6],
        ['name' => 'san carlos',  'superior' => 2],
        ['name' => 'caracoles',   'superior' => 6],
        ['name' => 'la reliquia', 'superior' => 7],
        ['name' => 'trece de mayo',   'superior' => 7],
        ['name' => 'sesquicentenario',    'superior' => 9],
        ['name' => 'villa claudia',   'superior' => 9],
        ['name' => 'la rosita',   'superior' => 9],
        ['name' => 'los centauros',   'superior' => 9],
        ['name' => 'cambulos',    'superior' => 9],
        ['name' => 'las acacias', 'superior' => 9],
        ['name' => 'piamonte',    'superior' => 10],
        ['name' => 'rosa linda',  'superior' => 9],
        ['name' => 'plena vida',  'superior' => 9],
        ['name' => 'esperanza 2000',  'superior' => 9],
        ['name' => 'villa hermosa ',  'superior' => 9],
        ['name' => 'aranjuez',    'superior' => 7],
        ['name' => 'bosques de vizcaya',  'superior' => 7],
        ['name' => 'calatraba del campo', 'superior' => 7],
        ['name' => 'canaguay',    'superior' => 7],
        ['name' => 'carolina',    'superior' => 7],
        ['name' => 'el nogal',    'superior' => 8],
        ['name' => 'cerro campestre', 'superior' => 7],
        ['name' => 'conqusta',    'superior' => 7],
        ['name' => 'montecarlo',  'superior' => 10],
        ['name' => 'los cedros',  'superior' => 4],
        ['name' => 'margaritas',  'superior' => 4],
        ['name' => 'mesetas', 'superior' => 4],
        ['name' => 'pozo 20', 'superior' => 4],
        ['name' => 'el espejo',   'superior' => 4],
        ['name' => 'seis de enero',   'superior' => 5],
        ['name' => 'santa fe',    'superior' => 5],
        ['name' => 'pastrana',    'superior' => 8],
        ['name' => 'caney',   'superior' => 8],
        ['name' => 'teusaca', 'superior' => 8],
        ['name' => 'lomonaco',    'superior' => 8],
        ['name' => 'sausalito',   'superior' => 8],
        ['name' => 'brisas del caney',    'superior' => 8],
        ['name' => 'nuevo maizaro',   'superior' => 8],
        ['name' => 'san francisco',   'superior' => 10],
        ['name' => 'ciudad porfia',   'superior' => 10],
        ['name' => 'rincon de las lomas', 'superior' => 10],
        ['name' => 'nueva jerusalén', 'superior' => 10],
        ['name' => 'tigana',  'superior' => 10],
        ['name' => 'pablo emilio riveros',    'superior' => 11],
        ['name' => 'vda santa teresita',  'superior' => 11],
        ['name' => 'vda santa rosa',  'superior' => 11],
        ['name' => 'vda san jose de las palomas', 'superior' => 11],
        ['name' => 'vda caño hondo',  'superior' => 11],
        ['name' => 'cooperativo', 'superior' => 11],
        ['name' => 'vda montebello',  'superior' => 11],
        ['name' => 'vda quebraditas', 'superior' => 11],
        ['name' => 'vda el carmen',   'superior' => 11],
        ['name' => 'el retorno',  'superior' => 11],
        ['name' => 'inspeccion san isidro de chichimene', 'superior' => 11],
        ['name' => 'villa del sol',   'superior' => 11],
        ['name' => 'las acacias', 'superior' => 11],
        ['name' => 'la florida',  'superior' => 11],
        ['name' => 'vda rancho grande',   'superior' => 11],
        ['name' => 'los olivos',  'superior' => 11],
        ['name' => 'vda vista hermosa',   'superior' => 11],
        ['name' => 'mancera', 'superior' => 11],
        ['name' => 'la independencia',    'superior' => 11],
        ['name' => 'vda el resguardo',    'superior' => 11],
        ['name' => 'santa isabel',    'superior' => 11],
        ['name' => 'vda las margaritas',  'superior' => 11],
        ['name' => 'vda la pradera',  'superior' => 11],
        ['name' => 'vda el diamante', 'superior' => 11],
        ['name' => 'asociación de amigos',    'superior' => 11],
        ['name' => 'vda brisas del guayuriba',    'superior' => 11],
        ['name' => 'vda las blancas', 'superior' => 11],
        ['name' => 'samán',   'superior' => 11],
        ['name' => 'centro',  'superior' => 11],
        ['name' => 'vda alto acaciitas',  'superior' => 11],
        ['name' => 'vda patio bonito',    'superior' => 11],
        ['name' => 'vda el centro',   'superior' => 11],
        ['name' => 'vda monte libano',    'superior' => 11],
        ['name' => 'vda alto acacias',    'superior' => 11],
        ['name' => 'guaratara',   'superior' => 11],
        ['name' => 'vda san jose',    'superior' => 11],
        ['name' => 'palermo', 'superior' => 11],
        ['name' => 'brisas del playon',   'superior' => 11],
        ['name' => 'vda la palma',    'superior' => 11],
        ['name' => 'morichal',    'superior' => 11],
        ['name' => 'vda laberinto',   'superior' => 11],
        ['name' => 'vda el triunfo',  'superior' => 11],
        ['name' => 'vda san nicolas', 'superior' => 11],
        ['name' => 'bella suiza', 'superior' => 11],
        ['name' => 'vda la primavera',    'superior' => 11],
        ['name' => 'vda san cayetano',    'superior' => 11],
        ['name' => 'popular', 'superior' => 11],
        ['name' => 'las violetas',    'superior' => 11],
        ['name' => 'san josé',    'superior' => 11],
        ['name' => 'altos de bachue', 'superior' => 11],
        ['name' => 'la tiza', 'superior' => 11],
        ['name' => 'la unión',    'superior' => 11],
        ['name' => 'el jardin de dinamarca',  'superior' => 11],
        ['name' => 'san cristobal',   'superior' => 11],
        ['name' => 'el bosque',   'superior' => 11],
        ['name' => 'el dorado',   'superior' => 11],
        ['name' => 'la colina',   'superior' => 11],
        ['name' => 'villa teresa',    'superior' => 11],
        ['name' => 'juan mellao', 'superior' => 11],
        ['name' => 'vda la cecilita', 'superior' => 11],
        ['name' => 'vda la esmeralda',    'superior' => 11],
        ['name' => 'vda fresco valle',    'superior' => 11],
        ['name' => 'nutivara',    'superior' => 11],
        ['name' => 'vda la union san isidro de chichimene',   'superior' => 11],
        ['name' => 'vda loma del pañuelo',    'superior' => 11],
        ['name' => 'vda san juanito', 'superior' => 11],
        ['name' => 'cimarron',    'superior' => 11],
        ['name' => 'vda la loma', 'superior' => 11],
        ['name' => 'bachue 4 etapa danubio',  'superior' => 11],
        ['name' => 'villa del llano', 'superior' => 11],
        ['name' => 'vda sardinata',   'superior' => 11],
        ['name' => 'las vegas',   'superior' => 11],
        ['name' => 'vda portachuelo', 'superior' => 11],
        ['name' => 'las ferias',  'superior' => 11],
        ['name' => 'vda alto  manacacias',    'superior' => 11],
        ['name' => 'vda loma de tigre',   'superior' => 11],
        ['name' => 'comcaja', 'superior' => 11],
        ['name' => 'ciudad jardín',   'superior' => 11],
        ['name' => 'inspección de dinamarca', 'superior' => 11],
        ['name' => 'vda el playon',   'superior' => 11],
        ['name' => 'vda el rosario',  'superior' => 11],
        ['name' => 'vda manzanares',  'superior' => 11],
        ['name' => 'vda san cristobal',   'superior' => 11],
        ['name' => 'vda los pinos',   'superior' => 11],
        ['name' => 'vda loma de san juan',    'superior' => 11],
        ['name' => 'villa del prado', 'superior' => 11],
        ['name' => 'villa lucia', 'superior' => 11],
        ['name' => 'don bosco',   'superior' => 11],
        ['name' => 'nuevo horizonte', 'superior' => 11],
        ['name' => 'paraiso', 'superior' => 11],
        ['name' => 'vda montelibano - sector bajo',   'superior' => 11],
        ['name' => 'los verdes',  'superior' => 11],
        ['name' => 'veinte de julio', 'superior' => 11],
        ['name' => 'bachue',  'superior' => 11],
        ['name' => 'alborada',    'superior' => 11],
        ['name' => 'independencia',   'superior' => 11],
        ['name' => 'las colinas', 'superior' => 11],
        ['name' => 'villa aurora',    'superior' => 11],
        ['name' => 'divino niã‘o jesus',  'superior' => 11],
        ['name' => 'retorno', 'superior' => 11],
        ['name' => 'asoviviendas',    'superior' => 11],
        ['name' => 'nueva victoria',  'superior' => 11],
        ['name' => 'los laureles',    'superior' => 11],
        ['name' => 'via malecon', 'superior' => 11],
        ['name' => 'via la chorrera', 'superior' => 11],
        ['name' => 'alcaravan',   'superior' => 11],
        ['name' => 'pablo sexto', 'superior' => 11],
        ['name' => 'everest', 'superior' => 11],
        ['name' => 'via antigua a guamal',    'superior' => 11],
        ['name' => 'las brisas',  'superior' => 11],
        ['name' => 'villa rueda', 'superior' => 11],
        ['name' => 'villa suiza', 'superior' => 11],
        ['name' => 'malecom turistico',   'superior' => 11],
        ['name' => 'la primavera',    'superior' => 11],
        ['name' => 'dorado bajo', 'superior' => 11],
        ['name' => 'portales de san carlos',  'superior' => 11],
        ['name' => 'araguaney',   'superior' => 11],
        ['name' => 'san isidro de chichimene',    'superior' => 11],
        ['name' => 'prado',   'superior' => 11],
        ['name' => 'el bambu',    'superior' => 11],
        ['name' => 'villateresa', 'superior' => 11],
        ['name' => 'dorado alto', 'superior' => 11],
        ['name' => 'la estrella', 'superior' => 11],
        ['name' => 'bancarios',   'superior' => 11],
        ['name' => 'atahualpa',   'superior' => 11],
        ['name' => 'prados de codem', 'superior' => 11],
        ['name' => 'villa hermosa',   'superior' => 11],
        ['name' => 'santa ana',   'superior' => 11],
        ['name' => 'san camilo',  'superior' => 11],
        ['name' => 'panorama',    'superior' => 11],
        ['name' => 'palma real',  'superior' => 11],
        ['name' => 'pablo vi',    'superior' => 11],
        ['name' => 'el nogal',    'superior' => 11],
        ['name' => 'malibu',  'superior' => 11],
        ['name' => 'llanomar',    'superior' => 11],
        ['name' => 'las villas',  'superior' => 11],
        ['name' => 'las gaviotas',    'superior' => 11],
        ['name' => 'la pradera',  'superior' => 11],
        ['name' => 'la palma',    'superior' => 11],
        ['name' => 'la hormiga',  'superior' => 11],
        ['name' => 'grupo comercial los 18',  'superior' => 11],
        ['name' => 'el lago', 'superior' => 11],
        ['name' => 'ciudadela el constructor',    'superior' => 11],
        ['name' => 'ciudadela los angeles',   'superior' => 11],
        ['name' => 'balcones de san diego',   'superior' => 11],
        ['name' => 'balcones de santa isabel',    'superior' => 11],
        ['name' => 'la carolina', 'superior' => 11],
        ['name' => 'villa esperanza', 'superior' => 11],
        ['name' => 'cristo rey',  'superior' => 11],
        ['name' => 'altos de covicom',    'superior' => 11],
        ['name' => 'villa maguensy',  'superior' => 11],
        ['name' => 'villa fontana',   'superior' => 11],
        ['name' => 'los naranjos',    'superior' => 11],
        ['name' => 'condado nuevo milenio',   'superior' => 11],
        ['name' => 'arrayanes',   'superior' => 11],
        ['name' => 'el jardin',   'superior' => 11],
        ['name' => 'balmoral',    'superior' => 11],
        ['name' => 'los pinos',   'superior' => 11],
        ['name' => 'los cedritos',    'superior' => 11],
        ['name' => 'el saman',    'superior' => 11],
        ['name' => 'florida', 'superior' => 11],
        ['name' => 'el trebol',   'superior' => 11],
        ['name' => 'carolina',    'superior' => 11],
        ['name' => 'la joyita',   'superior' => 11],
        ['name' => 'covicom', 'superior' => 11],
        ['name' => 'llano verde', 'superior' => 11],
        ['name' => 'villalucia',  'superior' => 11],
        ['name' => 'villa magali',    'superior' => 11],
        ['name' => 'el playon',   'superior' => 11],
        ['name' => 'el diamante', 'superior' => 11],
        ['name' => 'sardinata',   'superior' => 11],
        ['name' => 'el carmen ',  'superior' => 11],
        ['name' => 'san nicolas', 'superior' => 11],
        ['name' => 'la esmeralda ',   'superior' => 11],
        ['name' => 'resguardo',   'superior' => 11],
        ['name' => 'nueva jerusalem', 'superior' => 11],
        ['name' => 'vereda san pablo',    'superior' => 11],
        ['name' => 'vda el algarrobo',    'superior' => 12],
        ['name' => 'vda el  hijoa',   'superior' => 12],
        ['name' => 'vda las moras',   'superior' => 12],
        ['name' => 'vda los pavitos', 'superior' => 12],
        ['name' => 'vda san ignacio', 'superior' => 12],
        ['name' => 'la libertad primera etapa',   'superior' => 12],
        ['name' => 'pueblo nuevo',    'superior' => 12],
        ['name' => 'el prado',    'superior' => 12],
        ['name' => 'guaicaramo',  'superior' => 12],
        ['name' => 'inspeccion guayabal de upia', 'superior' => 13],
        ['name' => 'inspeccion viso de upia', 'superior' => 13],
        ['name' => 'vda san miguel',  'superior' => 13],
        ['name' => 'vda yarico',  'superior' => 13],
        ['name' => 'vda palomas', 'superior' => 13],
        ['name' => 'vda naguaya alto',    'superior' => 13],
        ['name' => 'centro',  'superior' => 13],
        ['name' => 'juan pablo ii',   'superior' => 13],
        ['name' => 'vda la embajada', 'superior' => 13],
        ['name' => 'vda san isidro',  'superior' => 13],
        ['name' => 'vda las delicias ',   'superior' => 13],
        ['name' => 'vda san miguel',  'superior' => 13],
        ['name' => 'vda san pedro',   'superior' => 13],
        ['name' => 'pescadores',  'superior' => 13],
        ['name' => 'vda central de san juanito',  'superior' => 14],
        ['name' => 'villa milena',    'superior' => 14],
        ['name' => 'la shell',    'superior' => 14],
        ['name' => 'vda cacayal', 'superior' => 14],
        ['name' => 'vda el turuy',    'superior' => 14],
        ['name' => 'vda san antonio', 'superior' => 14],
        ['name' => 'vda barro blanco',    'superior' => 14],
        ['name' => 'vda betania', 'superior' => 14],
        ['name' => 'vda caño grande', 'superior' => 14],
        ['name' => 'olga lucia',  'superior' => 14],
        ['name' => 'vda las violetas',    'superior' => 14],
        ['name' => 'vda arenales',    'superior' => 14],
        ['name' => 'vda sabanas del rosario', 'superior' => 14],
        ['name' => 'vda caño grande alto',    'superior' => 14],
        ['name' => 'vda el toro', 'superior' => 14],
        ['name' => 'vda san lorenzo', 'superior' => 14],
        ['name' => 'vda san agustin', 'superior' => 14],
        ['name' => 'villa checoop',   'superior' => 14],
        ['name' => 'centro',  'superior' => 14],
        ['name' => 'caja agraria',    'superior' => 14],
        ['name' => 'la carolina', 'superior' => 14],
        ['name' => 'el paraiso',  'superior' => 14],
        ['name' => 'el progreso', 'superior' => 14],
        ['name' => 'villa luz',   'superior' => 15],
        ['name' => 'vda brisas del tonoa',    'superior' => 15],
        ['name' => 'vda la libertad alta',    'superior' => 15],
        ['name' => 'vda puerto ariari',   'superior' => 15],
        ['name' => 'vda el vergel',   'superior' => 15],
        ['name' => 'vda monserrate',  'superior' => 15],
        ['name' => 'vda marayal', 'superior' => 15],
        ['name' => 'vda el central',  'superior' => 15],
        ['name' => 'vda aguas claras',    'superior' => 15],
        ['name' => 'vda rio azul',    'superior' => 15],
        ['name' => 'vda el jujuaro',  'superior' => 15],
        ['name' => 'vda vergel alto', 'superior' => 15],
        ['name' => 'vda la union',    'superior' => 15],
        ['name' => 'vda mesa redonda',    'superior' => 15],
        ['name' => 'vda san miguel',  'superior' => 15],
        ['name' => 'vda la amistad',  'superior' => 15],
        ['name' => 'vda arrayanes',   'superior' => 15],
        ['name' => 'vda la libertad', 'superior' => 15],
        ['name' => 'vda el retiro',   'superior' => 15],
        ['name' => 'vda santa barbara',   'superior' => 15],
        ['name' => 'el jardin',   'superior' => 15],
        ['name' => 'el prado',    'superior' => 15],
        ['name' => 'san pedro',   'superior' => 15],
        ['name' => 'maspinos-sinay',  'superior' => 15],
        ['name' => 'vda palomas', 'superior' => 15],
        ['name' => 'santa lucia', 'superior' => 15],
        ['name' => 'vda bellavista',  'superior' => 15],
        ['name' => 'obrero',  'superior' => 16],
        ['name' => 'vda san joaquin', 'superior' => 16],
        ['name' => 'vda laguna brava',    'superior' => 16],
        ['name' => 'centro',  'superior' => 16],
        ['name' => 'el condado',  'superior' => 16],
        ['name' => 'vda la venturosa',    'superior' => 16],
        ['name' => 'el prado',    'superior' => 16],
        ['name' => 'la solidaridad',  'superior' => 16],
        ['name' => 'vda chepero', 'superior' => 16],
        ['name' => 'vda el yari', 'superior' => 16],
        ['name' => 'el portal del llano', 'superior' => 16],
        ['name' => 'simon bolivar',   'superior' => 16],
        ['name' => 'parcelacion el bosque',   'superior' => 16],
        ['name' => 'villa  adriana',  'superior' => 16],
        ['name' => 'los limones', 'superior' => 16],
        ['name' => 'inspeccion caney medio',  'superior' => 16],
        ['name' => 'los moriches',    'superior' => 16],
        ['name' => 'monserrate',  'superior' => 16],
        ['name' => 'villa olimpica',  'superior' => 16],
        ['name' => 'inspeccion san nicolas',  'superior' => 16],
        ['name' => 'inspeccion caibe',    'superior' => 16],
        ['name' => 'inspeccion de guacavia',  'superior' => 16],
        ['name' => 'inspeccion de varsovia',  'superior' => 16],
        ['name' => 'el triunfo',  'superior' => 16],
        ['name' => 'villa nidia', 'superior' => 16],
        ['name' => 'inspeccion veracruz', 'superior' => 16],
        ['name' => 'inspeccion de presentado',    'superior' => 16],
        ['name' => 'fundadores',  'superior' => 16],
        ['name' => 'bello horizonte', 'superior' => 16],
        ['name' => 'la primavera',    'superior' => 16],
        ['name' => 'inspeccion montebello',   'superior' => 16],
        ['name' => 'villa cumare',    'superior' => 16],
        ['name' => 'vda cuarteles',   'superior' => 16],
        ['name' => 'emprendedores',   'superior' => 16],
        ['name' => 'los nuevos pinos',    'superior' => 16],
        ['name' => 'inspeccion de monfort',   'superior' => 17],
        ['name' => 'vda el carmen',   'superior' => 17],
        ['name' => 'central', 'superior' => 17],
        ['name' => 'vda el cedro',    'superior' => 17],
        ['name' => 'vda el palmar',   'superior' => 17],
        ['name' => 'vda lourdes', 'superior' => 17],
        ['name' => 'vda san francisco',   'superior' => 17],
        ['name' => 'vda san pedro',   'superior' => 17],
        ['name' => 'vda san rafael',  'superior' => 17],
        ['name' => 'vda santa maria', 'superior' => 17],
        ['name' => 'vda san lus de laderas',  'superior' => 17],
        ['name' => 'vda mesetas', 'superior' => 17],
        ['name' => 'vda san agustin', 'superior' => 17],
        ['name' => 'vda la cristalina',   'superior' => 17],
        ['name' => 'vda san isidro bajo', 'superior' => 17],
        ['name' => 'vda san antonio alto',    'superior' => 17],
        ['name' => 'vda san antonio', 'superior' => 18],
        ['name' => 'nueva esperanza', 'superior' => 18],
        ['name' => 'vda santa cruz',  'superior' => 18],
        ['name' => 'vda san luis de yamanes', 'superior' => 18],
        ['name' => 'vda rio viejo',   'superior' => 18],
        ['name' => 'vda playa rica',  'superior' => 18],
        ['name' => 'vda malabar', 'superior' => 18],
        ['name' => 'vda los alpes',   'superior' => 18],
        ['name' => 'vda la macarena', 'superior' => 18],
        ['name' => 'vda la gloria',   'superior' => 18],
        ['name' => 'vda la floresta', 'superior' => 18],
        ['name' => 'el jardin',   'superior' => 18],
        ['name' => 'vda el encanto',  'superior' => 18],
        ['name' => 'vda el delirio',  'superior' => 18],
        ['name' => 'vda la cumbre',   'superior' => 18],
        ['name' => 'inspeccion medellin del ariari',  'superior' => 18],
        ['name' => 'santander',   'superior' => 18],
        ['name' => 'alfonso meneses', 'superior' => 18],
        ['name' => 'vda alto de la  cal', 'superior' => 18],
        ['name' => 'vda caño tigre',  'superior' => 18],
        ['name' => 'vda carmen uno',  'superior' => 18],
        ['name' => 'vda el cable',    'superior' => 18],
        ['name' => 'vda cumaral bajo',    'superior' => 18],
        ['name' => 'vda el reposo',   'superior' => 18],
        ['name' => 'vda caño dulce',  'superior' => 18],
        ['name' => 'vda caño embarrado',  'superior' => 18],
        ['name' => 'vda brisas de yamanes',   'superior' => 18],
        ['name' => 'vda campo alegre',    'superior' => 18],
        ['name' => 'centro',  'superior' => 18],
        ['name' => 'vda la union',    'superior' => 18],
        ['name' => 'vda la argelia',  'superior' => 18],
        ['name' => 'vda caño claro',  'superior' => 18],
        ['name' => 'vda caño leche',  'superior' => 18],
        ['name' => 'vda caño lindo',  'superior' => 18],
        ['name' => 'vda el reflejo',  'superior' => 18],
        ['name' => 'vda el  retiro',  'superior' => 18],
        ['name' => 'vda la cima', 'superior' => 18],
        ['name' => 'vda la esmeralda',    'superior' => 18],
        ['name' => 'vda miravalles',  'superior' => 18],
        ['name' => 'puerto esperanza',    'superior' => 18],
        ['name' => 'vda el jardin',   'superior' => 18],
        ['name' => 'vda san isidro del ariari',   'superior' => 19],
        ['name' => 'vda la cumbre',   'superior' => 19],
        ['name' => 'vda la esmeralda',    'superior' => 19],
        ['name' => 'vda san jose',    'superior' => 19],
        ['name' => 'vda san pedro',   'superior' => 19],
        ['name' => 'vda la meseta',   'superior' => 19],
        ['name' => 'vda la isla sector ii',   'superior' => 19],
        ['name' => 'vda caño leche',  'superior' => 19],
        ['name' => 'vda caño amarillo',   'superior' => 19],
        ['name' => 'vda santa rosa del ariari',   'superior' => 19],
        ['name' => 'vda el diamante', 'superior' => 19],
        ['name' => 'vda alto ariari', 'superior' => 19],
        ['name' => 'vda agua zarcas', 'superior' => 19],
        ['name' => 'vda alto cumaral',    'superior' => 19],
        ['name' => 'central', 'superior' => 19],
        ['name' => 'vda pueblo sanchez',  'superior' => 19],
        ['name' => 'villa paz',   'superior' => 19],
        ['name' => 'vda la cooperativa',  'superior' => 20],
        ['name' => 'vda el porvenir', 'superior' => 20],
        ['name' => 'vda el kiosco',   'superior' => 20],
        ['name' => 'vda caño loro',   'superior' => 20],
        ['name' => 'vda caño blanco', 'superior' => 20],
        ['name' => 'vda caño venado', 'superior' => 20],
        ['name' => 'vda bajo sardinata',  'superior' => 20],
        ['name' => 'vda avichure',    'superior' => 20],
        ['name' => 'vda alto sardinata',  'superior' => 20],
        ['name' => 'vda alto guanayas',   'superior' => 20],
        ['name' => 'vda la luna', 'superior' => 20],
        ['name' => 'vda barranco colorado',   'superior' => 20],
        ['name' => 'villa margarita', 'superior' => 20],
        ['name' => 'el libertador',   'superior' => 20],
        ['name' => 'el lago', 'superior' => 20],
        ['name' => 'el triunfo',  'superior' => 20],
        ['name' => 'vda puerto esperanza',    'superior' => 20],
        ['name' => 'vda puerto aljure',   'superior' => 20],
        ['name' => 'la primavera',    'superior' => 20],
        ['name' => 'vda mogotes', 'superior' => 20],
        ['name' => 'vda tranquitas',  'superior' => 20],
        ['name' => 'vda uricacha',    'superior' => 20],
        ['name' => 'vda la union del ariari', 'superior' => 20],
        ['name' => 'vda villa restrepo',  'superior' => 20],
        ['name' => 'vda puerto santander',    'superior' => 20],
        ['name' => 'vda puerto poveda',   'superior' => 20],
        ['name' => 'vda puerto palma',    'superior' => 20],
        ['name' => 'vda puerto nuevo',    'superior' => 20],
        ['name' => 'vda puerto limon',    'superior' => 20],
        ['name' => 'vda bajo guanayas',   'superior' => 20],
        ['name' => 'las brisas',  'superior' => 20],
        ['name' => 'vda eltriunfo',   'superior' => 20],
        ['name' => 'sumarraga',   'superior' => 20],
        ['name' => 'vda el triunfo dos',  'superior' => 20],
        ['name' => 'vda maracaibo',   'superior' => 20],
        ['name' => 'buenos aires',    'superior' => 20],
        ['name' => 'vda las delicias',    'superior' => 20],
        ['name' => 'vda zanja de raya',   'superior' => 20],
        ['name' => 'villa salem', 'superior' => 21],
        ['name' => 'ciudadela pedagogica',    'superior' => 21],
        ['name' => 'vda la mariela',  'superior' => 21],
        ['name' => 'vda la mariela',  'superior' => 21],
        ['name' => 'vda la palmilla', 'superior' => 21],
        ['name' => 'vda la rivera',   'superior' => 21],
        ['name' => 'vda la union dos quebradas',  'superior' => 21],
        ['name' => 'vda la isla', 'superior' => 21],
        ['name' => 'vda los andes',   'superior' => 21],
        ['name' => 'verdea florida alta', 'superior' => 21],
        ['name' => 'vda los mangos',  'superior' => 21],
        ['name' => 'verda guayaquil', 'superior' => 21],
        ['name' => 'vda los maracos', 'superior' => 21],
        ['name' => 'luis carlos riveros', 'superior' => 21],
        ['name' => 'vda mucuya',  'superior' => 21],
        ['name' => 'vda patio bonito',    'superior' => 21],
        ['name' => 'vda la cabaña',   'superior' => 21],
        ['name' => 'nueva granada',   'superior' => 21],
        ['name' => 'vda la cubillera',    'superior' => 21],
        ['name' => 'vda santa helena',    'superior' => 21],
        ['name' => 'vda sardinata',   'superior' => 21],
        ['name' => 'vda la florida',  'superior' => 21],
        ['name' => 'antonio ricaurte',    'superior' => 21],
        ['name' => 'vda el delirio',  'superior' => 21],
        ['name' => 'alfonso montoya pava',    'superior' => 21],
        ['name' => 'vda el darien',   'superior' => 21],
        ['name' => 'brisas de irique',    'superior' => 21],
        ['name' => 'belen',   'superior' => 21],
        ['name' => 'vda el crucero',  'superior' => 21],
        ['name' => 'camilo torres',   'superior' => 21],
        ['name' => 'vda dos quebradas',   'superior' => 21],
        ['name' => 'vda san ignacio', 'superior' => 21],
        ['name' => 'central', 'superior' => 21],
        ['name' => 'vda guanayas trocha once',    'superior' => 21],
        ['name' => 'vda el guape',    'superior' => 21],
        ['name' => 'ciudad florida',  'superior' => 21],
        ['name' => 'el amparo',   'superior' => 21],
        ['name' => 'inspeccion la playa', 'superior' => 21],
        ['name' => 'el jardin',   'superior' => 21],
        ['name' => 'inspeccion de puerto caldas', 'superior' => 21],
        ['name' => 'el bosque',   'superior' => 21],
        ['name' => 'el popular  ',    'superior' => 21],
        ['name' => 'inspeccion de canaguaro', 'superior' => 21],
        ['name' => 'el progreso', 'superior' => 21],
        ['name' => 'inspeccion aguas claras', 'superior' => 21],
        ['name' => 'villas de granada',   'superior' => 21],
        ['name' => 'el triunfo',  'superior' => 21],
        ['name' => 'jorge eliecer gaitan',    'superior' => 21],
        ['name' => 'villa olimpica',  'superior' => 21],
        ['name' => 'la inmaculada',   'superior' => 21],
        ['name' => 'las delicias',    'superior' => 21],
        ['name' => 'san juan bosco',  'superior' => 21],
        ['name' => 'vda urichare trocha siete',   'superior' => 21],
        ['name' => 'primero de junio',    'superior' => 21],
        ['name' => 'villa union', 'superior' => 21],
        ['name' => 'brisas del ariari',   'superior' => 21],
        ['name' => 'el diamante', 'superior' => 21],
        ['name' => 'vda puerto suarez',   'superior' => 21],
        ['name' => 'vda aguas claras sec la cubillera',   'superior' => 21],
        ['name' => 'vda alto  irique',    'superior' => 21],
        ['name' => 'el estero',   'superior' => 21],
        ['name' => 'el porvenir', 'superior' => 21],
        ['name' => 'vda la esperanza',    'superior' => 21],
        ['name' => 'simon bolivar',   'superior' => 21],
        ['name' => 'el caney',    'superior' => 21],
        ['name' => 'vda caño rojo',   'superior' => 21],
        ['name' => 'vda las brisas',  'superior' => 21],
        ['name' => 'vda el centro',   'superior' => 21],
        ['name' => 'las villas',  'superior' => 22],
        ['name' => 'vda montecristo', 'superior' => 22],
        ['name' => 'vda el danubio',  'superior' => 22],
        ['name' => 'vda el retiro',   'superior' => 22],
        ['name' => 'vda la isla', 'superior' => 22],
        ['name' => 'la floresta', 'superior' => 22],
        ['name' => 'las ferias',  'superior' => 22],
        ['name' => 'vda la paz',  'superior' => 22],
        ['name' => 'vda monserrate',  'superior' => 22],
        ['name' => 'vda pio xii', 'superior' => 22],
        ['name' => 'vda santa ana',   'superior' => 22],
        ['name' => 'vda san miguel',  'superior' => 22],
        ['name' => 'inspeccion humadea',  'superior' => 22],
        ['name' => 'las villas',  'superior' => 22],
        ['name' => 'vda orotoy',  'superior' => 22],
        ['name' => 'los fundadores',  'superior' => 22],
        ['name' => 'vda santa barbara',   'superior' => 22],
        ['name' => 'vda el dorado',   'superior' => 22],
        ['name' => 'vda el encanto',  'superior' => 22],
        ['name' => 'vda monserrate bajo', 'superior' => 22],
        ['name' => 'vda santa teresa',    'superior' => 22],
        ['name' => 'vda el carmen',   'superior' => 22],
        ['name' => 'bosques de santa bárbara',    'superior' => 22],
        ['name' => 'centro',  'superior' => 22],
        ['name' => 'el paraíso',  'superior' => 22],
        ['name' => 'villa claudia',   'superior' => 22],
        ['name' => 'vda guacamayas',  'superior' => 26],
        ['name' => 'vda el aguila',   'superior' => 26],
        ['name' => 'vda el delirio',  'superior' => 26],
        ['name' => 'vda canapure',    'superior' => 26],
        ['name' => 'vda la cooperativa',  'superior' => 26],
        ['name' => 'vda puerto siare',    'superior' => 26],
        ['name' => 'vda caño siria',  'superior' => 26],
        ['name' => 'vda los merecures',   'superior' => 26],
        ['name' => 'rincon del indio',    'superior' => 26],
        ['name' => 'vda bonanza', 'superior' => 26],
        ['name' => 'inspeccion el mielon',    'superior' => 26],
        ['name' => 'vda el danubio',  'superior' => 26],
        ['name' => 'inspeccion el anzuelo',   'superior' => 26],
        ['name' => 'vda el silencio', 'superior' => 26],
        ['name' => 'vda caño ovejas', 'superior' => 26],
        ['name' => 'vda el progreso', 'superior' => 26],
        ['name' => 'vda la curva',    'superior' => 26],
        ['name' => 'los esteros bajos',   'superior' => 26],
        ['name' => 'vda mata bambu',  'superior' => 26],
        ['name' => 'vda san fernando',    'superior' => 26],
        ['name' => 'vda santa helena',    'superior' => 26],
        ['name' => 'inspeccion de sardinata', 'superior' => 26],
        ['name' => 'vda san antonio', 'superior' => 26],
        ['name' => 'vda los esteros altos',   'superior' => 26],
        ['name' => 'vda el diamante', 'superior' => 27],
        ['name' => 'vda alto cafre',  'superior' => 27],
        ['name' => 'vda las brumas',  'superior' => 27],
        ['name' => 'jardin',  'superior' => 27],
        ['name' => 'vda las flores',  'superior' => 27],
        ['name' => 'vda guaimaral',   'superior' => 27],
        ['name' => 'vda el trique',   'superior' => 27],
        ['name' => 'vda  las mercedes',   'superior' => 27],
        ['name' => 'vda las rosas',   'superior' => 27],
        ['name' => 'vda el mirador',  'superior' => 27],
        ['name' => 'vda la frontera', 'superior' => 27],
        ['name' => 'vda la guajira',  'superior' => 27],
        ['name' => 'vda la libertad', 'superior' => 27],
        ['name' => 'vda la marina',   'superior' => 27],
        ['name' => 'vda la paz',  'superior' => 27],
        ['name' => 'vda la reforma',  'superior' => 27],
        ['name' => 'vda la union',    'superior' => 27],
        ['name' => 'vda las brisas',  'superior' => 27],
        ['name' => 'villa lucia', 'superior' => 27],
        ['name' => 'vda las palmeras',    'superior' => 27],
        ['name' => 'vda los alpes',   'superior' => 27],
        ['name' => 'vda los naranjos',    'superior' => 27],
        ['name' => 'vda montañitas',  'superior' => 27],
        ['name' => 'vda monte bello', 'superior' => 27],
        ['name' => 'vda morro bello', 'superior' => 27],
        ['name' => 'vda nueva esperanza', 'superior' => 27],
        ['name' => 'vda nuevo porvenir',  'superior' => 27],
        ['name' => 'vda oriente', 'superior' => 27],
        ['name' => 'vda payandesal',  'superior' => 27],
        ['name' => 'vda puerto nariño',   'superior' => 27],
        ['name' => 'vda san antonio', 'superior' => 27],
        ['name' => 'vda san fernando',    'superior' => 27],
        ['name' => 'vda san isidro',  'superior' => 27],
        ['name' => 'vda san miguel',  'superior' => 27],
        ['name' => 'vda santa helena',    'superior' => 27],
        ['name' => 'vda jardin  de  las peñas',   'superior' => 27],
        ['name' => 'vda las colinas', 'superior' => 27],
        ['name' => 'vda el piñal',    'superior' => 27],
        ['name' => 'vda el palmar',   'superior' => 27],
        ['name' => 'vda el porvenir', 'superior' => 27],
        ['name' => 'vda bajo cuncia', 'superior' => 27],
        ['name' => 'vda alto andes',  'superior' => 27],
        ['name' => 'barrialosa',  'superior' => 27],
        ['name' => 'vda el gobernador',   'superior' => 27],
        ['name' => 'vda buena vista', 'superior' => 27],
        ['name' => 'vda la floresta', 'superior' => 27],
        ['name' => 'vda guacamayas',  'superior' => 27],
        ['name' => 'vda brisas del duda', 'superior' => 27],
        ['name' => 'vda la cristalina',   'superior' => 27],
        ['name' => 'centro',  'superior' => 27],
        ['name' => 'vda betania', 'superior' => 27],
        ['name' => 'vda  el sinai',   'superior' => 27],
        ['name' => 'vda cafetales',   'superior' => 27],
        ['name' => 'vda el turpial',  'superior' => 27],
        ['name' => 'vda el cairo',    'superior' => 27],
        ['name' => 'vda manantial',   'superior' => 27],
        ['name' => 'vda la florida',  'superior' => 27],
        ['name' => 'vda la argentina',    'superior' => 27],
        ['name' => 'la cabaña',   'superior' => 27],
        ['name' => 'vda el paraiso',  'superior' => 27],
        ['name' => 'vda bajo andes',  'superior' => 27],
        ['name' => 'vda la cominera', 'superior' => 27],
        ['name' => 'vda horizonte',   'superior' => 27],
        ['name' => 'el jazmin',   'superior' => 27],
        ['name' => 'el prado',    'superior' => 27],
        ['name' => 'provivienda', 'superior' => 27],
        ['name' => 'vda buenos aires',    'superior' => 27],
        ['name' => 'vda el paraiso',  'superior' => 23],
        ['name' => 'vda brisas del lozada',   'superior' => 23],
        ['name' => 'vda california',  'superior' => 23],
        ['name' => 'vda el retiro',   'superior' => 23],
        ['name' => 'vda el rubi', 'superior' => 23],
        ['name' => 'vda la argentina',    'superior' => 23],
        ['name' => 'vda la catalina', 'superior' => 23],
        ['name' => 'vda la cristalina del lozada',    'superior' => 23],
        ['name' => 'vda la esmeralda',    'superior' => 23],
        ['name' => 'vda los alpes',   'superior' => 23],
        ['name' => 'vda los andes',   'superior' => 23],
        ['name' => 'vda los medios',  'superior' => 23],
        ['name' => 'vda los laureles',    'superior' => 23],
        ['name' => 'vda la palestina',    'superior' => 23],
        ['name' => 'vda tres chorros',    'superior' => 23],
        ['name' => 'vda playa rica',  'superior' => 23],
        ['name' => 'vda san jose',    'superior' => 23],
        ['name' => 'vda san juan de lozada',  'superior' => 23],
        ['name' => 'vda san martin',  'superior' => 23],
        ['name' => 'vda santa teresa',    'superior' => 23],
        ['name' => 'vda yarumales',   'superior' => 23],
        ['name' => 'vda tercer milenio',  'superior' => 23],
        ['name' => 'vda caño raya',   'superior' => 23],
        ['name' => 'vda altamira',    'superior' => 23],
        ['name' => 'vda el oasis',    'superior' => 23],
        ['name' => 'vda la florida',  'superior' => 23],
        ['name' => 'vda alto morrocoy',   'superior' => 23],
        ['name' => 'vda bajo lozada', 'superior' => 23],
        ['name' => 'vda bajo raudal', 'superior' => 23],
        ['name' => 'vda nuevo milenio',   'superior' => 23],
        ['name' => 'vda buenos aires',    'superior' => 23],
        ['name' => 'vda bajo san antonio',    'superior' => 23],
        ['name' => 'vda la union',    'superior' => 23],
        ['name' => 'vda el carmen',   'superior' => 23],
        ['name' => 'vda  campohermoso',   'superior' => 23],
        ['name' => 'vda bocas del perdido',   'superior' => 23],
        ['name' => 'vda el diamante', 'superior' => 23],
        ['name' => 'vda la orquidea', 'superior' => 23],
        ['name' => 'vda aires del meta',  'superior' => 23],
        ['name' => 'vda central caño gringo', 'superior' => 23],
        ['name' => 'vda el jordan',   'superior' => 23],
        ['name' => 'vda el palmar uno',   'superior' => 23],
        ['name' => 'vda aguazul', 'superior' => 23],
        ['name' => 'vda caño azul',   'superior' => 23],
        ['name' => 'las colinas', 'superior' => 23],
        ['name' => 'vda caño mono',   'superior' => 23],
        ['name' => 'vda getsemani',   'superior' => 23],
        ['name' => 'el porvenir', 'superior' => 23],
        ['name' => 'vda el tapir',    'superior' => 23],
        ['name' => 'vda el turpial',  'superior' => 23],
        ['name' => 'vda la laguna',   'superior' => 23],
        ['name' => 'vda la ilusion',  'superior' => 23],
        ['name' => 'vda el carmen dos',   'superior' => 23],
        ['name' => 'vda el palenque', 'superior' => 23],
        ['name' => 'vda bajo recreo', 'superior' => 23],
        ['name' => 'vda el vergel',   'superior' => 23],
        ['name' => 'vda la brasilia', 'superior' => 23],
        ['name' => 'vda la cachivera',    'superior' => 23],
        ['name' => 'vda aguas claras',    'superior' => 23],
        ['name' => 'vda alpes bajo',  'superior' => 23],
        ['name' => 'los cristales',   'superior' => 23],
        ['name' => 'vda las delicias',    'superior' => 23],
        ['name' => 'vda el recreo',   'superior' => 23],
        ['name' => 'centro',  'superior' => 23],
        ['name' => 'vda portales del llano',  'superior' => 23],
        ['name' => 'antonio nariño',  'superior' => 23],
        ['name' => 'vda el limonar',  'superior' => 23],
        ['name' => 'brisas del guayabero',    'superior' => 23],
        ['name' => 'vda el silencio', 'superior' => 23],
        ['name' => 'vda ruvictoria',  'superior' => 23],
        ['name' => 'vda potras quebradon',    'superior' => 23],
        ['name' => 'vda peña roja',   'superior' => 23],
        ['name' => 'vda el caiman',   'superior' => 23],
        ['name' => 'vda el topacio dos',  'superior' => 23],
        ['name' => 'vda el porvenir uno', 'superior' => 23],
        ['name' => 'bellavista',  'superior' => 23],
        ['name' => 'vda aires del perdido',   'superior' => 23],
        ['name' => 'vda  el yari',    'superior' => 23],
        ['name' => 'vda alto esperanza',  'superior' => 23],
        ['name' => 'vda caño rojo',   'superior' => 23],
        ['name' => 'vda centro poblado san francisco de la sombra',   'superior' => 23],
        ['name' => 'vda el indio',    'superior' => 23],
        ['name' => 'vda el morichal', 'superior' => 23],
        ['name' => 'vda el palmar dos',   'superior' => 23],
        ['name' => 'vda el progreso', 'superior' => 23],
        ['name' => 'vda alto raudal', 'superior' => 23],
        ['name' => 'vda el triunfo',  'superior' => 23],
        ['name' => 'vda la atlantida',    'superior' => 23],
        ['name' => 'vda la batalla',  'superior' => 23],
        ['name' => 'vda la cabaña',   'superior' => 23],
        ['name' => 'vda la dorada',   'superior' => 23],
        ['name' => 'vda la fundacion',    'superior' => 23],
        ['name' => 'vda las nieves',  'superior' => 23],
        ['name' => 'vda los naranjos',    'superior' => 23],
        ['name' => 'vda miraflores',  'superior' => 23],
        ['name' => 'vda palmar bajo', 'superior' => 23],
        ['name' => 'vda paraiso union',   'superior' => 23],
        ['name' => 'vda primavera del lozada',    'superior' => 23],
        ['name' => 'vda alto san antonio',    'superior' => 23],
        ['name' => 'vda versalles',   'superior' => 23],
        ['name' => 'vda caño mono dos',   'superior' => 23],
        ['name' => 'vegas del guayabero', 'superior' => 23],
        ['name' => 'vda la batalla dos',  'superior' => 23],
        ['name' => 'vda la tunia',    'superior' => 23],
        ['name' => 'vda el billar',   'superior' => 23],
        ['name' => 'vda bocas de caño gringo',    'superior' => 23],
        ['name' => 'vda alto jardin', 'superior' => 23],
        ['name' => 'eden del tigre sector alto',  'superior' => 23],
        ['name' => 'primavera del lozada ',   'superior' => 23],
        ['name' => 'vda caño gringo medio',   'superior' => 23],
        ['name' => 'vda el diamante dos', 'superior' => 23],
        ['name' => 'vda la esperanza',    'superior' => 23],
        ['name' => 'vda las delicias ii', 'superior' => 23],
        ['name' => 'vda aguas claras dos',    'superior' => 23],
        ['name' => 'vda salto yarumales', 'superior' => 23],
        ['name' => 'vda  centro duda',    'superior' => 24],
        ['name' => 'vda los tempranos',   'superior' => 24],
        ['name' => 'vda palmar bajo', 'superior' => 24],
        ['name' => 'vda la sonora',   'superior' => 24],
        ['name' => 'vda los tambos',  'superior' => 24],
        ['name' => 'vda alto palmar', 'superior' => 24],
        ['name' => 'central', 'superior' => 24],
        ['name' => 'vda buenos aires',    'superior' => 24],
        ['name' => 'vda candilejas',  'superior' => 24],
        ['name' => 'vda el brasil',   'superior' => 24],
        ['name' => 'vda el diamante', 'superior' => 24],
        ['name' => 'vda el diviso',   'superior' => 24],
        ['name' => 'vda mirador', 'superior' => 24],
        ['name' => 'vda el paraiso',  'superior' => 24],
        ['name' => 'vda el placer',   'superior' => 24],
        ['name' => 'vda el progreso', 'superior' => 24],
        ['name' => 'vda el recreo',   'superior' => 24],
        ['name' => 'vda el tigre',    'superior' => 24],
        ['name' => 'vda el vergel',   'superior' => 24],
        ['name' => 'vda la amistad',  'superior' => 24],
        ['name' => 'vda la argelia',  'superior' => 24],
        ['name' => 'vda la belleza',  'superior' => 24],
        ['name' => 'vda espelda', 'superior' => 24],
        ['name' => 'vda la   esperanza',  'superior' => 24],
        ['name' => 'vda la estrella', 'superior' => 24],
        ['name' => 'vda explanacion', 'superior' => 24],
        ['name' => 'vda la floresta', 'superior' => 24],
        ['name' => 'inspeccion la julia', 'superior' => 24],
        ['name' => 'vda la paz',  'superior' => 24],
        ['name' => 'vda la pista',    'superior' => 24],
        ['name' => 'vda la primavera',    'superior' => 24],
        ['name' => 'vda la siria',    'superior' => 24],
        ['name' => 'vda la union',    'superior' => 24],
        ['name' => 'vda las camelias',    'superior' => 24],
        ['name' => 'vda las gaviotas',    'superior' => 24],
        ['name' => 'vda las rosas',   'superior' => 24],
        ['name' => 'vda los planes',  'superior' => 24],
        ['name' => 'vda mancitas',    'superior' => 24],
        ['name' => 'vda montealegre', 'superior' => 24],
        ['name' => 'vda nueva libertad',  'superior' => 24],
        ['name' => 'vda palestina',   'superior' => 24],
        ['name' => 'vda papamene',    'superior' => 24],
        ['name' => 'vda puerto crevaux',  'superior' => 24],
        ['name' => 'vda san carlos',  'superior' => 24],
        ['name' => 'vda santander',   'superior' => 24],
        ['name' => 'vda tierra adentro',  'superior' => 24],
        ['name' => 'vda versalles',   'superior' => 24],
        ['name' => 'vda yavia',   'superior' => 24],
        ['name' => 'industrial',  'superior' => 24],
        ['name' => 'el jardin',   'superior' => 24],
        ['name' => 'vda caño paujil', 'superior' => 24],
        ['name' => 'vda comuneros',   'superior' => 24],
        ['name' => 'vda el roble',    'superior' => 25],
        ['name' => 'vda naranjal',    'superior' => 25],
        ['name' => 'vda la cabaña',   'superior' => 25],
        ['name' => 'centro',  'superior' => 25],
        ['name' => 'manantial',   'superior' => 25],
        ['name' => 'vda alta cristalina', 'superior' => 25],
        ['name' => 'vda la aurora',   'superior' => 25],
        ['name' => 'vda el paraiso',  'superior' => 25],
        ['name' => 'vda buenos aires',    'superior' => 25],
        ['name' => 'vda alto lejanias',   'superior' => 25],
        ['name' => 'modelo',  'superior' => 25],
        ['name' => 'vda lucitania',   'superior' => 25],
        ['name' => 'vda agua linda',  'superior' => 25],
        ['name' => 'vda cacayal', 'superior' => 25],
        ['name' => 'vda angosturas del guape',    'superior' => 25],
        ['name' => 'vda las margaritas',  'superior' => 25],
        ['name' => 'vda la española', 'superior' => 25],
        ['name' => 'vda mira valle',  'superior' => 25],
        ['name' => 'vda la cristalina',   'superior' => 25],
        ['name' => 'vda el diamante', 'superior' => 25],
        ['name' => 'vda la veinticuatro', 'superior' => 25],
        ['name' => 'vda el convenio', 'superior' => 25],
        ['name' => 'vda bella vista', 'superior' => 25],
        ['name' => 'pedro nel jimenez',   'superior' => 25],
        ['name' => 'vda el topacio',  'superior' => 25],
        ['name' => 'vda guarumal',    'superior' => 25],
        ['name' => 'vda el brillante',    'superior' => 25],
        ['name' => 'vda cafetales',   'superior' => 25],
        ['name' => 'vda san ignacio', 'superior' => 25],
        ['name' => 'vda las camelias',    'superior' => 25],
        ['name' => 'vda los laureles',    'superior' => 25],
        ['name' => 'vda las delicias',    'superior' => 25],
        ['name' => 'simon bolivar',   'superior' => 25],
        ['name' => 'vda agua bonita', 'superior' => 25],
        ['name' => 'vda la albania',  'superior' => 25],
        ['name' => 'vda el jardin',   'superior' => 25],
        ['name' => 'vda yucape',  'superior' => 25],
        ['name' => 'vda bocas del ariari',    'superior' => 28],
        ['name' => 'vda santa isabel',    'superior' => 28],
        ['name' => 'el retiro',   'superior' => 28],
        ['name' => 'el diamante', 'superior' => 28],
        ['name' => 'vda alto mielon', 'superior' => 28],
        ['name' => 'vda san fernando',    'superior' => 28],
        ['name' => 'vda playa alta',  'superior' => 28],
        ['name' => 'vda lindenal',    'superior' => 28],
        ['name' => 'vda el tesoro',   'superior' => 28],
        ['name' => 'vda las guarupayas',  'superior' => 28],
        ['name' => 'vda los andes',   'superior' => 28],
        ['name' => 'vda santa lucia', 'superior' => 28],
        ['name' => 'vda aguas claras',    'superior' => 28],
        ['name' => 'vda caño ceiba alto', 'superior' => 28],
        ['name' => 'primero de mayo', 'superior' => 28],
        ['name' => 'divino niño', 'superior' => 28],
        ['name' => 'porvenir',    'superior' => 28],
        ['name' => 'vda el paraiso',  'superior' => 28],
        ['name' => 'vda la florida',  'superior' => 28],
        ['name' => 'vda cruce del pororio',   'superior' => 28],
        ['name' => 'vda caño la sal', 'superior' => 28],
        ['name' => 'vda caño marimba',    'superior' => 28],
        ['name' => 'vda la cristalina',   'superior' => 28],
        ['name' => 'vda el palmar',   'superior' => 28],
        ['name' => 'vda salitre', 'superior' => 28],
        ['name' => 'vda la cascada',  'superior' => 28],
        ['name' => 'vda la union',    'superior' => 28],
        ['name' => 'vda playa nueva', 'superior' => 28],
        ['name' => 'vda puerto colombia', 'superior' => 28],
        ['name' => 'vda  puerto cacao',   'superior' => 28],
        ['name' => 'vda la gran primavera',   'superior' => 28],
        ['name' => 'vda chaparrito',  'superior' => 28],
        ['name' => 'vda las mercedes',    'superior' => 28],
        ['name' => 'alto cafre',  'superior' => 28],
        ['name' => 'vda la libertad', 'superior' => 29],
        ['name' => 'manacacias',  'superior' => 29],
        ['name' => 'vda alto el tigre',   'superior' => 29],
        ['name' => 'vda santa helena',    'superior' => 29],
        ['name' => 'popular', 'superior' => 29],
        ['name' => 'el triunfo',  'superior' => 29],
        ['name' => 'villa ortiz', 'superior' => 29],
        ['name' => 'vdas nuevas fundaciones', 'superior' => 29],
        ['name' => 'vda san pedro de arimena',    'superior' => 29],
        ['name' => 'vda planas',  'superior' => 29],
        ['name' => 'vda el porvenir', 'superior' => 29],
        ['name' => 'galan',   'superior' => 29],
        ['name' => 'la esperanza',    'superior' => 29],
        ['name' => 'vda san miguel',  'superior' => 29],
        ['name' => 'vda puente arimena',  'superior' => 29],
        ['name' => 'los alpes',   'superior' => 29],
        ['name' => 'vda murujuy', 'superior' => 29],
        ['name' => 'centro',  'superior' => 29],
        ['name' => 'inspeccion puerto trujillo',  'superior' => 29],
        ['name' => 'inspeccion la cristalina',    'superior' => 29],
        ['name' => 'perla del manacacias',    'superior' => 29],
        ['name' => 'vda santa barbara  guasipati',    'superior' => 29],
        ['name' => 'vda tillava', 'superior' => 29],
        ['name' => 'vda alto neblinas',   'superior' => 29],
        ['name' => 'vda santa catalina',  'superior' => 29],
        ['name' => 'el trampolin',    'superior' => 29],
        ['name' => 'vda carimagua',   'superior' => 29],
        ['name' => 'alto manacacias', 'superior' => 29],
        ['name' => 'carimagua',   'superior' => 29],
        ['name' => 'vda matarraton',  'superior' => 29],
        ['name' => 'vda comejenal',   'superior' => 29],
        ['name' => 'vencedores',  'superior' => 29],
        ['name' => 'vda guasipati',   'superior' => 29],
        ['name' => 'perla de manacacias  villa amalia',   'superior' => 29],
        ['name' => 'paraiso natural', 'superior' => 29],
        ['name' => 'bello horizonte', 'superior' => 29],
        ['name' => 'inspeccion de remolino',  'superior' => 30],
        ['name' => 'abel rey',    'superior' => 30],
        ['name' => 'vda el turpial',  'superior' => 30],
        ['name' => 'inspeccion el tigre', 'superior' => 30],
        ['name' => 'jorge eliecer gaitan',    'superior' => 30],
        ['name' => 'la victoria', 'superior' => 30],
        ['name' => 'comuneros',   'superior' => 30],
        ['name' => 'bajo navajas',    'superior' => 30],
        ['name' => 'ciudad jardin',   'superior' => 30],
        ['name' => 'bello horizonte', 'superior' => 30],
        ['name' => 'menegua', 'superior' => 30],
        ['name' => 'vda el porvenir', 'superior' => 30],
        ['name' => 'el vergel',   'superior' => 30],
        ['name' => 'villa modelia',   'superior' => 30],
        ['name' => 'vda melua medio', 'superior' => 30],
        ['name' => 'el prado',    'superior' => 30],
        ['name' => 'la venturosa',    'superior' => 30],
        ['name' => 'los mangos',  'superior' => 30],
        ['name' => 'inspeccion de la balsa',  'superior' => 30],
        ['name' => 'vda alto melua',  'superior' => 30],
        ['name' => 'vda brisas del guatiquia',    'superior' => 30],
        ['name' => 'vda puerto porfia',   'superior' => 30],
        ['name' => 'vda alto navajas',    'superior' => 30],
        ['name' => 'vda patagonia',   'superior' => 30],
        ['name' => 'san luis de rio negro',   'superior' => 30],
        ['name' => 'la union',    'superior' => 30],
        ['name' => 'inspeccion chaviva',  'superior' => 30],
        ['name' => 'porvenir',    'superior' => 30],
        ['name' => 'julio flores',    'superior' => 30],
        ['name' => 'nueve de abril',  'superior' => 30],
        ['name' => 'guadalupe salcedo',   'superior' => 30],
        ['name' => 'vda bajo melua',  'superior' => 30],
        ['name' => 'la laguna',   'superior' => 30],
        ['name' => 'vda bocas del guayuriba', 'superior' => 30],
        ['name' => 'inspeccion puerto guadalupe', 'superior' => 30],
        ['name' => 'santander',   'superior' => 30],
        ['name' => 'vda marayal', 'superior' => 30],
        ['name' => 'policarpa',   'superior' => 30],
        ['name' => 'vda guichiral',   'superior' => 30],
        ['name' => 'vda altamira',    'superior' => 30],
        ['name' => 'inspeccion de pachaquiaro',   'superior' => 30],
        ['name' => 'vda alto yucao',  'superior' => 30],
        ['name' => 'vda pueblo nuevo',    'superior' => 30],
        ['name' => 'manzanares inspección de pachaquiaro',    'superior' => 30],
        ['name' => 'vda la serrania', 'superior' => 30],
        ['name' => 'vda nare',    'superior' => 30],
        ['name' => 'vda las leonas',  'superior' => 30],
        ['name' => 'vda las delicias',    'superior' => 30],
        ['name' => 'villa suiza', 'superior' => 30],
        ['name' => 'vda rubiales',    'superior' => 31],
        ['name' => 'vda  chinata',    'superior' => 31],
        ['name' => 'vda el caribe',   'superior' => 31],
        ['name' => 'vda el diamante', 'superior' => 31],
        ['name' => 'vda cunimia charco trece',    'superior' => 31],
        ['name' => 'vda islandia',    'superior' => 31],
        ['name' => 'vda el cairo',    'superior' => 31],
        ['name' => 'vda la esperanza',    'superior' => 31],
        ['name' => 'vda los fundadores',  'superior' => 31],
        ['name' => 'vda la tigrera',  'superior' => 31],
        ['name' => 'vda la union',    'superior' => 31],
        ['name' => 'gaitan',  'superior' => 31],
        ['name' => 'vda villa de la paz', 'superior' => 31],
        ['name' => 'vda  los laureles',   'superior' => 31],
        ['name' => 'vda caño rayado', 'superior' => 31],
        ['name' => 'vda palmeras',    'superior' => 31],
        ['name' => 'la esperanza',    'superior' => 31],
        ['name' => 'vocacional',  'superior' => 31],
        ['name' => 'popular', 'superior' => 31],
        ['name' => 'vda puerto principe', 'superior' => 31],
        ['name' => 'porvenir',    'superior' => 31],
        ['name' => 'vda canada',  'superior' => 31],
        ['name' => 'vda tierra grata',    'superior' => 31],
        ['name' => 'vda agua linda',  'superior' => 31],
        ['name' => 'vda brisas del guejar',   'superior' => 31],
        ['name' => 'vda esmeralda  dos',  'superior' => 31],
        ['name' => 'vda casibare',    'superior' => 31],
        ['name' => 'vda alto casibare',   'superior' => 31],
        ['name' => 'vda campo alegre',    'superior' => 31],
        ['name' => 'vda alto cunimia',    'superior' => 31],
        ['name' => 'vda el santuario',    'superior' => 31],
        ['name' => 'vda la argentina',    'superior' => 31],
        ['name' => 'vda alto manacacias', 'superior' => 31],
        ['name' => 'vda esmeraldo uno',   'superior' => 31],
        ['name' => 'vda  jose maria', 'superior' => 31],
        ['name' => 'vda la argelia',  'superior' => 32],
        ['name' => 'vda el jordan',   'superior' => 32],
        ['name' => 'vda san pedro',   'superior' => 32],
        ['name' => 'vda miravalles',  'superior' => 32],
        ['name' => 'vda palmeras',    'superior' => 32],
        ['name' => 'vda bocas de caño danta', 'superior' => 32],
        ['name' => 'vda caño blanco', 'superior' => 32],
        ['name' => 'vda la pradera',  'superior' => 32],
        ['name' => 'el jardin',   'superior' => 32],
        ['name' => 'vda la tigra',    'superior' => 32],
        ['name' => 'vda alto san vicente',    'superior' => 32],
        ['name' => 'vda puerto chispas',  'superior' => 32],
        ['name' => 'vda la hermita',  'superior' => 32],
        ['name' => 'vda agua linda',  'superior' => 32],
        ['name' => 'vda caño alfa',   'superior' => 32],
        ['name' => 'vda el dorado',   'superior' => 32],
        ['name' => 'vda la primavera',    'superior' => 32],
        ['name' => 'vda la victoria', 'superior' => 32],
        ['name' => 'vda la lindoza',  'superior' => 32],
        ['name' => 'vda santa lucia', 'superior' => 32],
        ['name' => 'vda puerto toledo',   'superior' => 32],
        ['name' => 'vda la venada',   'superior' => 32],
        ['name' => 'vda charco danto',    'superior' => 32],
        ['name' => 'vda la sultana',  'superior' => 32],
        ['name' => 'morichal',    'superior' => 32],
        ['name' => 'villa garcia',    'superior' => 32],
        ['name' => 'vda sausalito',   'superior' => 32],
        ['name' => 'vda la cabaña',   'superior' => 32],
        ['name' => 'vda l',   'superior' => 32],
        ['name' => 'vda guacamayas',  'superior' => 32],
        ['name' => 'vda la rivera',   'superior' => 32],
        ['name' => 'vda el oasis',    'superior' => 32],
        ['name' => 'vda laguna gringo',   'superior' => 32],
        ['name' => 'vda san rafael',  'superior' => 32],
        ['name' => 'vda danubio uno', 'superior' => 32],
        ['name' => 'vda las colinas', 'superior' => 32],
        ['name' => 'centro',  'superior' => 32],
        ['name' => 'primavera',   'superior' => 32],
        ['name' => 'la ye',   'superior' => 32],
        ['name' => 'vda bajo fundadores', 'superior' => 32],
        ['name' => 'vda brisas de cafre', 'superior' => 32],
        ['name' => 'el darien',   'superior' => 32],
        ['name' => 'vda el palmar',   'superior' => 32],
        ['name' => 'vda la esperanza',    'superior' => 32],
        ['name' => 'barranco colorado',   'superior' => 32],
        ['name' => 'vda la reforma',  'superior' => 32],
        ['name' => 'vda los comuneros',   'superior' => 32],
        ['name' => 'vda monserrate',  'superior' => 32],
        ['name' => 'vda san vicente bajo',    'superior' => 32],
        ['name' => 'villa suarez dos',    'superior' => 32],
        ['name' => 'simon bolivar',   'superior' => 33],
        ['name' => 'vda salinas', 'superior' => 33],
        ['name' => 'el recreo',   'superior' => 33],
        ['name' => 'centro',  'superior' => 33],
        ['name' => 'vda cruce de guacavia',   'superior' => 33],
        ['name' => 'vda puente amarillo', 'superior' => 33],
        ['name' => 'ospina perez',    'superior' => 33],
        ['name' => 'villa reina', 'superior' => 33],
        ['name' => 'minuto de dios',  'superior' => 33],
        ['name' => 'vda  brisas de upin', 'superior' => 33],
        ['name' => 'manantial',   'superior' => 33],
        ['name' => 'el libertador',   'superior' => 33],
        ['name' => 'vda el caney bajo',   'superior' => 33],
        ['name' => 'vda caney alto',  'superior' => 33],
        ['name' => 'vda caney alto oriental', 'superior' => 33],
        ['name' => 'vda el caibe',    'superior' => 33],
        ['name' => 'vda san jorge',   'superior' => 33],
        ['name' => 'vda los medios',  'superior' => 33],
        ['name' => 'el progreso', 'superior' => 33],
        ['name' => 'jorge eliecer gaitan',    'superior' => 33],
        ['name' => 'las acacias', 'superior' => 33],
        ['name' => 'vda santa lucia', 'superior' => 33],
        ['name' => 'vda santa cecilia',   'superior' => 33],
        ['name' => 'vda miralindo',   'superior' => 33],
        ['name' => 'vda san isidro',  'superior' => 33],
        ['name' => 'vda balcones',    'superior' => 33],
        ['name' => 'villa santos',    'superior' => 33],
        ['name' => 'vda marayal', 'superior' => 33],
        ['name' => 'vda la floresta', 'superior' => 33],
        ['name' => 'los almendros',   'superior' => 33],
        ['name' => 'antonio nariño',  'superior' => 33],
        ['name' => 'vda la sardinata',    'superior' => 33],
        ['name' => 'vda vega grande', 'superior' => 33],
        ['name' => 'inspeccion la palmera',   'superior' => 34],
        ['name' => 'vda giramena',    'superior' => 34],
        ['name' => 'vda patagonia',   'superior' => 34],
        ['name' => 'la guaratara y el laguito',   'superior' => 34],
        ['name' => 'inspeccion de surimena',  'superior' => 34],
        ['name' => 'inspeccion rincon de pajure', 'superior' => 34],
        ['name' => 'manguita ',   'superior' => 34],
        ['name' => 'cambulos',    'superior' => 34],
        ['name' => 'la floresta y el palmar', 'superior' => 34],
        ['name' => 'vda candilejas',  'superior' => 34],
        ['name' => 'vda san jose',    'superior' => 35],
        ['name' => 'vda alto curia',  'superior' => 35],
        ['name' => 'vda alto del tigre',  'superior' => 35],
        ['name' => 'verda alto monserrate',   'superior' => 35],
        ['name' => 'vda angosturas',  'superior' => 35],
        ['name' => 'vda bajo curia',  'superior' => 35],
        ['name' => 'vda bella vista', 'superior' => 35],
        ['name' => 'vda bocas del zanza', 'superior' => 35],
        ['name' => 'vda brasilia',    'superior' => 35],
        ['name' => 'vda cerritos',    'superior' => 35],
        ['name' => 'vda corrales',    'superior' => 35],
        ['name' => 'vda alto cumaral',    'superior' => 35],
        ['name' => 'vda el bosque',   'superior' => 35],
        ['name' => 'vda el nuevo progreso',   'superior' => 35],
        ['name' => 'vda el vergel',   'superior' => 35],
        ['name' => 'vda guayabal',    'superior' => 35],
        ['name' => 'vda jardines de zansa',   'superior' => 35],
        ['name' => 'la esperanza',    'superior' => 35],
        ['name' => 'vda la glorieta', 'superior' => 35],
        ['name' => 'la libertad', 'superior' => 35],
        ['name' => 'vda mesa de fernandez',   'superior' => 35],
        ['name' => 'vda miraflores',  'superior' => 35],
        ['name' => 'vda monserrate',  'superior' => 35],
        ['name' => 'vda peñas blancas',   'superior' => 35],
        ['name' => 'vda puerto gaitan',   'superior' => 35],
        ['name' => 'vda quebrada honda',  'superior' => 35],
        ['name' => 'vda santander',   'superior' => 35],
        ['name' => 'vda sardinata',   'superior' => 35],
        ['name' => 'vda tacuya',  'superior' => 35],
        ['name' => 'vda el rosal',    'superior' => 35],
        ['name' => 'vda palomas', 'superior' => 35],
        ['name' => 'buenos aires',    'superior' => 35],
        ['name' => 'la fuente',   'superior' => 35],
        ['name' => 'las ferias',  'superior' => 35],
        ['name' => 'vda buenos aires',    'superior' => 35],
        ['name' => 'vda san roque nuevo', 'superior' => 36],
        ['name' => 'vda san roque',   'superior' => 36],
        ['name' => 'vda san luis del plan',   'superior' => 36],
        ['name' => 'vda el carmen',   'superior' => 36],
        ['name' => 'vda la candelaria',   'superior' => 36],
        ['name' => 'vda el tablon',   'superior' => 36],
        ['name' => 'vda san luis de toledo',  'superior' => 36],
        ['name' => 'vda san jose',    'superior' => 36],
        ['name' => 'vda gran chaparral',  'superior' => 37],
        ['name' => 'vda aribas',  'superior' => 37],
        ['name' => 'el prado',    'superior' => 37],
        ['name' => 'vda altamira',    'superior' => 37],
        ['name' => 'vda santa teresa de camoa',   'superior' => 37],
        ['name' => 'vda la bañadera', 'superior' => 37],
        ['name' => 'vda rincon de bolivar',   'superior' => 37],
        ['name' => 'olimpico',    'superior' => 37],
        ['name' => 'maipore', 'superior' => 37],
        ['name' => 'libertador',  'superior' => 37],
        ['name' => 'la feria',    'superior' => 37],
        ['name' => 'felix maria duran',   'superior' => 37],
        ['name' => 'los andes',   'superior' => 37],
        ['name' => 'iv centenario',   'superior' => 37],
        ['name' => 'vda brisas del manacacias',   'superior' => 37],
        ['name' => 'vda alto rubiano',    'superior' => 37],
        ['name' => 'once de noviembre',   'superior' => 37],
        ['name' => 'vda la guardiana',    'superior' => 37],
        ['name' => 'vda santa helena',    'superior' => 37],
        ['name' => 'vda la castañeda',    'superior' => 37],
        ['name' => 'primavera',   'superior' => 37],
        ['name' => 'vda bajo camoa',  'superior' => 37],
        ['name' => 'villa luz',   'superior' => 37],
        ['name' => 'algarrobo',   'superior' => 37],
        ['name' => 'pedro daza',  'superior' => 37],
        ['name' => 'vda el merey',    'superior' => 37],
        ['name' => 'vda la pascualera',   'superior' => 37],
        ['name' => 'vda alto iraca',  'superior' => 37],
        ['name' => 'vda camachera',   'superior' => 37],
        ['name' => 'el camoa',    'superior' => 37],
        ['name' => 'los fundadores',  'superior' => 37],
        ['name' => 'vda gualas bajo humadea', 'superior' => 37],
        ['name' => 'vda la reforma',  'superior' => 37],
        ['name' => 'vda la siberia',  'superior' => 37],
        ['name' => 'vda treinta viso colorado',   'superior' => 37],
        ['name' => 'vda las palmeras',    'superior' => 38],
        ['name' => 'vda  la balastrera margén izquierda', 'superior' => 38],
        ['name' => 'vda la palestina',    'superior' => 38],
        ['name' => 'vda  nueva colombia', 'superior' => 38],
        ['name' => 'vda buena vista', 'superior' => 38],
        ['name' => 'vda talanqueras', 'superior' => 38],
        ['name' => 'vda los andes',   'superior' => 38],
        ['name' => 'vda puerto esperanza',    'superior' => 38],
        ['name' => 'vda jerico',  'superior' => 38],
        ['name' => 'vda balastrera margen derecha',   'superior' => 38],
        ['name' => 'vda guapaya medio',   'superior' => 38],
        ['name' => 'vda alto termales',   'superior' => 38],
        ['name' => 'vda buenos aires',    'superior' => 38],
        ['name' => 'inspección maracaibo',    'superior' => 38],
        ['name' => 'vda campo alegre',    'superior' => 38],
        ['name' => 'vda caño veinte', 'superior' => 38],
        ['name' => 'vda caño cabra',  'superior' => 38],
        ['name' => 'vda el vergel',   'superior' => 38],
        ['name' => 'vda el porvenir', 'superior' => 38],
        ['name' => 'vda guadualito',  'superior' => 38],
        ['name' => 'vda el palmar',   'superior' => 38],
        ['name' => 'vda el danubio',  'superior' => 38],
        ['name' => 'vda balconcito',  'superior' => 38],
        ['name' => 'vda la borrascosa',   'superior' => 38],
        ['name' => 'vda la isla', 'superior' => 38],
        ['name' => 'vda guapaya bajo',    'superior' => 38],
        ['name' => 'vda la libertad', 'superior' => 38],
        ['name' => 'vda la albania',  'superior' => 38],
        ['name' => 'nuevo horizonte', 'superior' => 38],
        ['name' => 'el popular',  'superior' => 38],
        ['name' => 'san juan bosco',  'superior' => 38],
        ['name' => 'vda piñalito',    'superior' => 38],
        ['name' => 'centro',  'superior' => 38],
        ['name' => 'vda puerto esperanza margen izquierda',   'superior' => 38],
        ['name' => 'vda puerto alegre',   'superior' => 38],
        ['name' => 'puerto lucas margen izquierda',   'superior' => 38],
        ['name' => 'vda mata de bambu',   'superior' => 38],
        ['name' => 'las brisas',  'superior' => 38],
        ['name' => 'vda trocha la veintiseis',    'superior' => 38],
        ['name' => 'vda san jose de jamuco',  'superior' => 38],
        ['name' => 'vda la paz',  'superior' => 38],
        ['name' => 'vda agua linda',  'superior' => 38],
        ['name' => 'vda alto caño piedra',    'superior' => 38],
        ['name' => 'vda alto guaini', 'superior' => 38],
        ['name' => 'vda alto guapaya',    'superior' => 38],
        ['name' => 'vda alto las delicias',   'superior' => 38],
        ['name' => 'vda bocas de talanqueras',    'superior' => 38],
        ['name' => 'vda costa rica',  'superior' => 38],
        ['name' => 'vda cunumia', 'superior' => 38],
        ['name' => 'vda el progreso', 'superior' => 38],
        ['name' => 'vda el triunfo',  'superior' => 38],
        ['name' => 'vda el encanto',  'superior' => 38],
        ['name' => 'vda la argentina',    'superior' => 38],
        ['name' => 'vda la cabaña uno',   'superior' => 38],
        ['name' => 'vda la cooperativa',  'superior' => 38],
        ['name' => 'vda la cristalina',   'superior' => 38],
        ['name' => 'vda la española', 'superior' => 38],
        ['name' => 'la esperanza',    'superior' => 38],
        ['name' => 'vda la lealtad',  'superior' => 38],
        ['name' => 'vda la palomera', 'superior' => 38],
        ['name' => 'vda la reforma',  'superior' => 38],
        ['name' => 'vda las delicias',    'superior' => 38],
        ['name' => 'vda las animas',  'superior' => 38],
        ['name' => 'vda loma linda',  'superior' => 38],
        ['name' => 'vda los alpes',   'superior' => 38],
        ['name' => 'vda los pinos',   'superior' => 38],
        ['name' => 'vda los rosales', 'superior' => 38],
        ['name' => 'vda puerto lucas',    'superior' => 38],
        ['name' => 'vda caño san jose',   'superior' => 38],
    ];

    public function run()
    {
        $faker = Faker\Factory::create();
        
        Location::create([
            'name'      => 'meta',
            'type_id'   => 1,
            'electoral_potential'   => 20000,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'villavicencio',
            'type_id'   => 2,
            'electoral_potential'   => 5000,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 1',
            'type_id'   => 3,
            'electoral_potential'   => 200,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 2',
            'type_id'   => 3,
            'electoral_potential'   => 300,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 3',
            'type_id'   => 3,
            'electoral_potential'   => 100,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 4',
            'type_id'   => 3,
            'electoral_potential'   => 200,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 5',
            'type_id'   => 3,
            'electoral_potential'   => 300,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 6',
            'type_id'   => 3,
            'electoral_potential'   => 300,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 7',
            'type_id'   => 3,
            'electoral_potential'   => 200,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 8',
            'type_id'   => 3,
            'electoral_potential'   => 400,
            'superior'  => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);


        $municipalities = self::$municipalities;

        foreach ($municipalities as $minicipality) {         
            Location::create([
                'name' => $minicipality,
                'type_id'   => 2,
                'superior'  => 1,
                'electoral_potential'   => 0,
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime 
            ]);                
        }

        foreach (self::$neighborhoods as $neighborhood) {         
            Location::create([
                'name' => $neighborhood['name'],
                'type_id'   => 4,
                'superior'  => $neighborhood['superior'],
                'electoral_potential'   => 0,
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime 
            ]);                
        }
    }
}

?>