<?php 

use \Illuminate\Database\Seeder;
use Victorem\Entities\Location;

class LocationsVillavicencioTableSeeder extends Seeder
{
    public static $neighborhoods = [
        ['name' => 'antonio ricaute',  'superior' => 4],
        ['name' => 'brisas del guatiquia',    'superior' => 4],
        ['name' => 'las delicias',    'superior' => 4],
        ['name' => 'el porvenir', 'superior' => 4],
        ['name' => 'san gregorio',    'superior' => 4],
        ['name' => 'san isidro',  'superior' => 4],
        ['name' => 'santafe', 'superior' => 4],
        ['name' => 'santa ines',  'superior' => 4],
        ['name' => 'la vainilla', 'superior' => 4],
        ['name' => '20 de julio', 'superior' => 4],
        ['name' => 'villa  julia',    'superior' => 4],
        ['name' => 'portales del llano',  'superior' => 9],
        ['name' => 'villa del rio uno',   'superior' => 9],
        ['name' => 'montecarlo',  'superior' => 9],
        ['name' => 'ciudad porfia sector cuatro', 'superior' => 9],
        ['name' => 'playa rica',  'superior' => 9],
        ['name' => 'alamos sur montecarlo',   'superior' => 9],
        ['name' => 'catumare',    'superior' => 9],
        ['name' => 'ciudad jardin sector ciudadela cofrem',   'superior' => 9],
        ['name' => 'altos de guatape - guatape dos',  'superior' => 9],
        ['name' => 'villa marina',    'superior' => 9],
        ['name' => 'villa lorena',    'superior' => 9],
        ['name' => 'villa juliana',   'superior' => 9],
        ['name' => 'villa del rio dos',   'superior' => 9],
        ['name' => 'maria paz',   'superior' => 9],
        ['name' => 'villa sonia', 'superior' => 9],
        ['name' => 'las americas',    'superior' => 9],
        ['name' => 'villa milena',    'superior' => 9],
        ['name' => 'el divino niño',  'superior' => 9],
        ['name' => 'la rochela',  'superior' => 9],
        ['name' => 'san jorge cuarta etapa',  'superior' => 9],
        ['name' => 'el darien',   'superior' => 9],
        ['name' => 'nuevo amanecer',  'superior' => 9],
        ['name' => 'maranatha',   'superior' => 9],
        ['name' => 'los heroes',  'superior' => 9],
        ['name' => 'villas del ocoa', 'superior' => 9],
        ['name' => 'montecarlo sector tres',  'superior' => 9],
        ['name' => 'santa librada',   'superior' => 9],
        ['name' => 'caminos de montecarlo',   'superior' => 9],
        ['name' => 'ciudadela brasilia',  'superior' => 9],
        ['name' => 'ciudad porfia sector uno',    'superior' => 9],
        ['name' => 'porfia sector tres',  'superior' => 9],
        ['name' => 'villa samper',    'superior' => 9],
        ['name' => 'santa cecilia',   'superior' => 9],
        ['name' => 'bifamiliares  ariguani tres', 'superior' => 6],
        ['name' => 'gaviotas',    'superior' => 6],
        ['name' => 'villa alejandra', 'superior' => 6],
        ['name' => 'bochica uno', 'superior' => 6],
        ['name' => 'villa helena',    'superior' => 6],
        ['name' => 'menegua', 'superior' => 6],
        ['name' => 'villa ortiz i etapa', 'superior' => 6],
        ['name' => 'el estero',   'superior' => 6],
        ['name' => 'cataluña',    'superior' => 6],
        ['name' => 'cavivir', 'superior' => 6],
        ['name' => 'estero alto', 'superior' => 6],
        ['name' => 'barzal  bajo',    'superior' => 3],
        ['name' => 'las camelias',    'superior' => 6],
        ['name' => 'guadalajara', 'superior' => 6],
        ['name' => 'hacaritama dos y tres',   'superior' => 6],
        ['name' => 'villa del sol',   'superior' => 1],
        ['name' => 'hacaritama uno y cuatro', 'superior' => 6],
        ['name' => 'nueva floresta',  'superior' => 6],
        ['name' => 'la concepcion',   'superior' => 1],
        ['name' => 'la primavera',    'superior' => 1],
        ['name' => 'el danubio',  'superior' => 6],
        ['name' => 'macunaima cuatro',    'superior' => 6],
        ['name' => 'villa ortiz dos', 'superior' => 6],
        ['name' => 'acapulco',    'superior' => 6],
        ['name' => 'el remanso',  'superior' => 6],
        ['name' => 'bello horizonte', 'superior' => 6],
        ['name' => 'ay mi llanura',   'superior' => 6],
        ['name' => 'villa melida',    'superior' => 6],
        ['name' => 'popular', 'superior' => 6],
        ['name' => 'valles de la carolina',   'superior' => 6],
        ['name' => 'el paraiso',  'superior' => 5],
        ['name' => 'urabanizacion la carolina',   'superior' => 6],
        ['name' => 'kirpas',  'superior' => 6],
        ['name' => 'prados de siberia',   'superior' => 5],
        ['name' => 'villa johana dos',    'superior' => 1],
        ['name' => 'alamos santa rosa',   'superior' => 9],
        ['name' => 'ariguani',    'superior' => 6],
        ['name' => 'el recreo tres',  'superior' => 5],
        ['name' => 'el recreo',   'superior' => 5],
        ['name' => 'nueva colombia uno',  'superior' => 1],
        ['name' => 'nueva colombia dos',  'superior' => 1],
        ['name' => 'morichal',    'superior' => 5],
        ['name' => 'las malvinas',    'superior' => 1],
        ['name' => 'el milagro rosales',  'superior' => 5],
        ['name' => 'madrigal uno',    'superior' => 5],
        ['name' => 'el jordan',   'superior' => 5],
        ['name' => 'vencedores',  'superior' => 1],
        ['name' => 'hierbabuena', 'superior' => 5],
        ['name' => 'villa suarez',    'superior' => 5],
        ['name' => 'santa helena ',   'superior' => 5],
        ['name' => 'santa helena sector dos', 'superior' => 5],
        ['name' => 'san felipe',  'superior' => 5],
        ['name' => 'los rosales', 'superior' => 5],
        ['name' => 'vda caños negros sec  1 la reliquia', 'superior' => 6],
        ['name' => 'la florencia',    'superior' => 5],
        ['name' => 'la desmotadora',  'superior' => 5],
        ['name' => 'el delirio',  'superior' => 4],
        ['name' => 'cedritos',    'superior' => 5],
        ['name' => 'calamar', 'superior' => 5],
        ['name' => 'villa johana uno',    'superior' => 1],
        ['name' => 'castilla',    'superior' => 5],
        ['name' => 'el bambu',    'superior' => 5],
        ['name' => 'alcala',  'superior' => 5],
        ['name' => 'antonio villavicencio',   'superior' => 5],
        ['name' => 'catumare sector dos', 'superior' => 9],
        ['name' => 'vda las mercedes sector la union',    'superior' => 1],
        ['name' => 'san ignacio uno y dos',   'superior' => 1],
        ['name' => 'portales de nuevo horizonte', 'superior' => 9],
        ['name' => 'la isla sector playa rica',   'superior' => 9],
        ['name' => 'villa nieves',    'superior' => 1],
        ['name' => 'santander',   'superior' => 4],
        ['name' => 'el emporio',  'superior' => 2],
        ['name' => 'san marcos',  'superior' => 7],
        ['name' => 'la victoria', 'superior' => 2],
        ['name' => 'nueva granada',   'superior' => 2],
        ['name' => 'panorama',    'superior' => 2],
        ['name' => 'rondinela',   'superior' => 2],
        ['name' => 'santa josefa militar',    'superior' => 2],
        ['name' => 'el rosal',    'superior' => 2],
        ['name' => 'chapinerito alto',    'superior' => 2],
        ['name' => 'el recuerdo', 'superior' => 2],
        ['name' => 'jose antonio galan',  'superior' => 1],
        ['name' => 'el triunfo',  'superior' => 2],
        ['name' => 'siete de agosto', 'superior' => 3],
        ['name' => 'brisas de la esperanza',  'superior' => 8],
        ['name' => 'comuneros',   'superior' => 8],
        ['name' => 'siete de agosto bajo',    'superior' => 3],
        ['name' => 'cooperativo', 'superior' => 8],
        ['name' => 'san jose ',   'superior' => 3],
        ['name' => 'la salle',    'superior' => 3],
        ['name' => 'centauro',    'superior' => 8],
        ['name' => 'camilo torres',   'superior' => 3],
        ['name' => 'la coralina', 'superior' => 8],
        ['name' => 'los libertadores',    'superior' => 3],
        ['name' => 'esperanza sexta etapa',   'superior' => 8],
        ['name' => 'esperanza septima etapa', 'superior' => 8],
        ['name' => 'villas del buque',    'superior' => 1],
        ['name' => 'buque',   'superior' => 3],
        ['name' => 'el jardin',   'superior' => 8],
        ['name' => 'la  azotea',  'superior' => 3],
        ['name' => 'juan pablo segundo',  'superior' => 8],
        ['name' => 'multifamiliares la esperanza octava etapa',   'superior' => 8],
        ['name' => 'el palmar',   'superior' => 8],
        ['name' => 'rosa blanca oriental',    'superior' => 8],
        ['name' => 'san fernando',    'superior' => 3],
        ['name' => 'venecia', 'superior' => 5],
        ['name' => 'la alborada', 'superior' => 8],
        ['name' => 'las colinas', 'superior' => 3],
        ['name' => 'canaima', 'superior' => 7],
        ['name' => 'vda el cocuy',    'superior' => 1],
        ['name' => 'vda caños negros',    'superior' => 1],
        ['name' => 'el embudo',   'superior' => 7],
        ['name' => 'la florida',  'superior' => 7],
        ['name' => 'garcia bohorquez',    'superior' => 7],
        ['name' => 'vda barcelona',   'superior' => 1],
        ['name' => 'vda apiay',   'superior' => 1],
        ['name' => 'san cristobal',   'superior' => 1],
        ['name' => 'vda vegas del guayuriba', 'superior' => 1],
        ['name' => 'macarena',    'superior' => 7],
        ['name' => 'vda santa rosa de rio negro', 'superior' => 1],
        ['name' => 'guatiquia',   'superior' => 7],
        ['name' => 'vda el guamo',    'superior' => 1],
        ['name' => 'llano lindo', 'superior' => 1],
        ['name' => 'simon bolivar',   'superior' => 7],
        ['name' => 'san benito',  'superior' => 7],
        ['name' => 'vda el amor sector villahermosa', 'superior' => 1],
        ['name' => 'nuevo ricaute',   'superior' => 7],
        ['name' => 'vda alto de  pompeya',    'superior' => 1],
        ['name' => 'vda arrayanes',   'superior' => 1],
        ['name' => 'vda peralonso',   'superior' => 1],
        ['name' => 'vda la llanerita',    'superior' => 1],
        ['name' => 'vda san luis de ocoa',    'superior' => 1],
        ['name' => 'vda rio negrito', 'superior' => 1],
        ['name' => 'vda la vigia',    'superior' => 1],
        ['name' => 'santa marta', 'superior' => 8],
        ['name' => 'vda reforma la libertad', 'superior' => 1],
        ['name' => 'multifamiliar santa catalina',    'superior' => 1],
        ['name' => 'vda quebrada honda',  'superior' => 1],
        ['name' => 'vda san jose alto',   'superior' => 1],
        ['name' => 'vda san juan de ocoa',    'superior' => 1],
        ['name' => 'vda pipiral', 'superior' => 1],
        ['name' => 'vda el carmen',   'superior' => 1],
        ['name' => 'vda contadero',   'superior' => 1],
        ['name' => 'vda servita', 'superior' => 1],
        ['name' => 'vda santa maria baja',    'superior' => 1],
        ['name' => 'inspeccion puerto colombia',  'superior' => 1],
        ['name' => 'vda buena vista', 'superior' => 1],
        ['name' => 'vda san marcos de chafurray', 'superior' => 1],
        ['name' => 'villa bolivar',   'superior' => 8],
        ['name' => 'esperanza uno ',  'superior' => 8],
        ['name' => 'esperanza dos',   'superior' => 8],
        ['name' => 'la rosita primera y segunda etapa',   'superior' => 8],
        ['name' => 'parcelas brisas del ocoa',    'superior' => 1],
        ['name' => 'vda la poyata',   'superior' => 1],
        ['name' => 'hachon bella suiza',  'superior' => 1],
        ['name' => 'verdea puerto tembleque', 'superior' => 1],
        ['name' => 'villa patricia',  'superior' => 1],
        ['name' => 'el progreso', 'superior' => 5],
        ['name' => 'la pradera',  'superior' => 1],
        ['name' => 'vda la cecilia',  'superior' => 1],
        ['name' => 'doce de octubre', 'superior' => 2],
        ['name' => 'guatape', 'superior' => 9],
        ['name' => 'rincon de pompeya',   'superior' => 1],
        ['name' => 'el retiro',   'superior' => 7],
        ['name' => 'el refugio',  'superior' => 9],
        ['name' => 'san jorge',   'superior' => 9],
        ['name' => 'barzal alto sur', 'superior' => 3],
        ['name' => 'vda el amor sector primero de mayo',  'superior' => 1],
        ['name' => 'cantarrana ', 'superior' => 7],
        ['name' => 'la grama',    'superior' => 2],
        ['name' => 'nuevo horizonte', 'superior' => 9],
        ['name' => 'saman de la rivera',  'superior' => 1],
        ['name' => 'vda la concepción baja',  'superior' => 1],
        ['name' => 'vizcaya', 'superior' => 6],
        ['name' => 'vda vanguardia alta', 'superior' => 1],
        ['name' => 'vda santa helena baja',   'superior' => 1],
        ['name' => 'vda santa helena',    'superior' => 1],
        ['name' => 'vda san cristobal',   'superior' => 1],
        ['name' => 'el topacio',  'superior' => 1],
        ['name' => 'villa maria', 'superior' => 3],
        ['name' => 'centro',  'superior' => 3],
        ['name' => 'la ceiba',    'superior' => 5],
        ['name' => 'madrigal dos',    'superior' => 5],
        ['name' => 'manantial',   'superior' => 5],
        ['name' => 'subnormal los guaduales', 'superior' => 1],
        ['name' => 'triunfadores del ocoa',   'superior' => 1],
        ['name' => 'vda cairo medio', 'superior' => 1],
        ['name' => 'mesetas bajas sector dos',    'superior' => 3],
        ['name' => 'vda santa helena baja sector dos',    'superior' => 1],
        ['name' => 'vda vanguardia baja', 'superior' => 1],
        ['name' => 'vda palo marcado',    'superior' => 1],
        ['name' => 'carulu',  'superior' => 8],
        ['name' => 'villa humberto',  'superior' => 8],
        ['name' => 'teusaquillo', 'superior' => 8],
        ['name' => 'la bastilla', 'superior' => 5],
        ['name' => 'rosa blanca', 'superior' => 8],
        ['name' => 'sexta etapa b esperanza sec brisas del buque',    'superior' => 1],
        ['name' => 'vda el amor', 'superior' => 1],
        ['name' => 'vda quenane', 'superior' => 1],
        ['name' => 'vda palmichal',   'superior' => 1],
        ['name' => 'villa del oriente',   'superior' => 9],
        ['name' => 'cantarrana cuatro',   'superior' => 7],
        ['name' => 'bosques de rosa blanca',  'superior' => 8],
        ['name' => 'vda san isidro alto de la cumbre',    'superior' => 1],
        ['name' => 'ciudadela san antonio',   'superior' => 6],
        ['name' => 'chapinerito bajo',    'superior' => 2],
        ['name' => 'villas del alcaravan',    'superior' => 1],
        ['name' => 'la reliquia sector tres', 'superior' => 6],
        ['name' => 'cantarrana dos',  'superior' => 7],
        ['name' => 'la reliquia sector dos',  'superior' => 6],
        ['name' => 'la reliquia sector cuatro',   'superior' => 6],
        ['name' => 'remansos de rosa blanca', 'superior' => 8],
        ['name' => 'marsella',    'superior' => 7],
        ['name' => 'vda indostan',    'superior' => 1],
        ['name' => 'loma linda',  'superior' => 1],
        ['name' => 'la pradera',  'superior' => 1],
        ['name' => 'bosques de abajam',   'superior' => 5],
        ['name' => 'leon trece',  'superior' => 8],
        ['name' => 'industrial',  'superior' => 4],
        ['name' => 'jorge eliecer gaitan',    'superior' => 1],
        ['name' => 'marco antonio pinilla',   'superior' => 6],
        ['name' => 'villa encanto',   'superior' => 5],
        ['name' => 'villa fabiola',   'superior' => 5],
        ['name' => 'el rodeo',    'superior' => 5],
        ['name' => 'san carlos',  'superior' => 1],
        ['name' => 'viña del mar',    'superior' => 1],
        ['name' => 'catatumbo',   'superior' => 7],
        ['name' => 'ciudadela divino niño',   'superior' => 6],
        ['name' => 'la serrania', 'superior' => 8],
        ['name' => 'san jorge quinta etapa',  'superior' => 1],
        ['name' => 'vda la union',    'superior' => 1],
        ['name' => 'vda la union sector naturalia',   'superior' => 1],
        ['name' => 'vda montecarlo',  'superior' => 1],
        ['name' => 'vda buenos aires bajo',   'superior' => 1],
        ['name' => 'vda samaria', 'superior' => 1],
        ['name' => 'vda la argentina',    'superior' => 1],
        ['name' => 'vda santa maria alta',    'superior' => 1],
        ['name' => 'vda cairo bajo',  'superior' => 1],
        ['name' => 'vda lourdes', 'superior' => 1],
        ['name' => 'vda puente abadia',   'superior' => 1],
        ['name' => 'vda santa teresa',    'superior' => 1],
        ['name' => 'vda juan bosco caños negros', 'superior' => 1],
        ['name' => 'brisas del buque alto',   'superior' => 3],
        ['name' => 'rincon de las margaritas',    'superior' => 3],
        ['name' => 'la sabana',   'superior' => 1],
        ['name' => 'los cambulos',    'superior' => 2],
        ['name' => 'amaral',  'superior' => 7],
        ['name' => 'nueva jerusalem', 'superior' => 1],
        ['name' => 'villas del palmar',   'superior' => 8],
        ['name' => 'la isla', 'superior' => 3],
        ['name' => 'el caudal',   'superior' => 2],
        ['name' => 'vda cairo alto',  'superior' => 1],
        ['name' => 'vizcaya seis',    'superior' => 6],
        ['name' => 'la vega', 'superior' => 8],
        ['name' => 'ciudad salitre',  'superior' => 5],
        ['name' => 'sosiego', 'superior' => 1],
        ['name' => 'el consuelo', 'superior' => 1],
        ['name' => 'fikus',   'superior' => 6],
        ['name' => 'los maracos', 'superior' => 6],
        ['name' => 'trapiche',    'superior' => 3],
        ['name' => 'las ferias',  'superior' => 4],
        ['name' => 'san luis',    'superior' => 5],
        ['name' => 'olimpico',    'superior' => 6],
        ['name' => 'dos mil', 'superior' => 6],
        ['name' => 'gaitan',  'superior' => 4],
        ['name' => 'la lambada',  'superior' => 4],
        ['name' => 'villa carola',    'superior' => 9],
        ['name' => 'ariguanery',  'superior' => 9],
        ['name' => 'villa ortiz', 'superior' => 6],
        ['name' => 'macunaima',   'superior' => 6],
        ['name' => 'hacaritama',  'superior' => 6],
        ['name' => 'aguas claras',    'superior' => 6],
        ['name' => 'doña luz',    'superior' => 6],
        ['name' => 'buenos aires',    'superior' => 6],
        ['name' => 'seis de abril',   'superior' => 5],
        ['name' => 'el prado',    'superior' => 2],
        ['name' => 'covisan', 'superior' => 5],
        ['name' => 'cedral',  'superior' => 5],
        ['name' => 'los cerezos', 'superior' => 2],
        ['name' => 'la campiña',  'superior' => 2],
        ['name' => 'catalana',    'superior' => 2],
        ['name' => 'el poblado',  'superior' => 2],
        ['name' => 'manaure', 'superior' => 2],
        ['name' => 'virrey',  'superior' => 2],
        ['name' => 'nueva andalucia', 'superior' => 3],
        ['name' => 'villa julia', 'superior' => 4],
        ['name' => 'maizaro', 'superior' => 3],
        ['name' => 'villaflores', 'superior' => 3],
        ['name' => 'villacentro', 'superior' => 3],
        ['name' => 'camoa',   'superior' => 3],
        ['name' => 'balata',  'superior' => 3],
        ['name' => 'los pinos',   'superior' => 3],
        ['name' => 'bonanza', 'superior' => 3],
        ['name' => 'villa codem', 'superior' => 3],
        ['name' => 'balcones de toledo',  'superior' => 3],
        ['name' => 'sansouci',    'superior' => 3],
        ['name' => 'galan',   'superior' => 3],
        ['name' => 'pontevedra',  'superior' => 5],
        ['name' => 'san carlos',  'superior' => 1],
        ['name' => 'caracoles',   'superior' => 5],
        ['name' => 'la reliquia', 'superior' => 6],
        ['name' => 'trece de mayo',   'superior' => 6],
        ['name' => 'sesquicentenario',    'superior' => 8],
        ['name' => 'villa claudia',   'superior' => 8],
        ['name' => 'la rosita',   'superior' => 8],
        ['name' => 'los centauros',   'superior' => 8],
        ['name' => 'cambulos',    'superior' => 8],
        ['name' => 'las acacias', 'superior' => 8],
        ['name' => 'piamonte',    'superior' => 9],
        ['name' => 'rosa linda',  'superior' => 8],
        ['name' => 'plena vida',  'superior' => 8],
        ['name' => 'esperanza 2000',  'superior' => 8],
        ['name' => 'villa hermosa ',  'superior' => 8],
        ['name' => 'aranjuez',    'superior' => 6],
        ['name' => 'bosques de vizcaya',  'superior' => 6],
        ['name' => 'calatraba del campo', 'superior' => 6],
        ['name' => 'canaguay',    'superior' => 6],
        ['name' => 'carolina',    'superior' => 6],
        ['name' => 'el nogal',    'superior' => 7],
        ['name' => 'cerro campestre', 'superior' => 6],
        ['name' => 'conqusta',    'superior' => 6],
        ['name' => 'montecarlo',  'superior' => 9],
        ['name' => 'los cedros',  'superior' => 3],
        ['name' => 'margaritas',  'superior' => 3],
        ['name' => 'mesetas', 'superior' => 3],
        ['name' => 'pozo 20', 'superior' => 3],
        ['name' => 'el espejo',   'superior' => 3],
        ['name' => 'seis de enero',   'superior' => 4],
        ['name' => 'santa fe',    'superior' => 4],
        ['name' => 'pastrana',    'superior' => 7],
        ['name' => 'caney',   'superior' => 7],
        ['name' => 'teusaca', 'superior' => 7],
        ['name' => 'lomonaco',    'superior' => 7],
        ['name' => 'sausalito',   'superior' => 7],
        ['name' => 'brisas del caney',    'superior' => 7],
        ['name' => 'nuevo maizaro',   'superior' => 7],
        ['name' => 'san francisco',   'superior' => 9],
        ['name' => 'ciudad porfia',   'superior' => 9],
        ['name' => 'rincon de las lomas', 'superior' => 9],
        ['name' => 'nueva jerusalén', 'superior' => 9],
        ['name' => 'tigana',  'superior' => 9]
    ];

    public function run()
    {
        Location::create([
            'name'      => 'villavicencio',
            'type_id'   => 2,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 1',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 2',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 3',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 4',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 5',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 6',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 7',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        Location::create([
            'name' => 'comuna 8',
            'type_id'   => 3,
            'superior'  => 1,
            'created_at'    => new DateTime,
            'updated_at'    => new DateTime 
        ]);

        foreach (self::$neighborhoods as $neighborhood) {         
            Location::create([
                'name' => $neighborhood['name'],
                'type_id'   => 4,
                'superior'  => $neighborhood['superior'],
                'electoral_potential'   => 0,
                'created_at'    => new DateTime,
                'updated_at'    => new DateTime 
            ]);                
        }
    }
}

?>