<?php 

use \Illuminate\Database\Seeder;
use Victorem\Entities\Location;

class LocationsCundinamarcaTableSeeder extends Seeder
{
	public static $locations = [
		// Municipios de Cundinamarca
		['name' => 'CUNDIMANARCA', 			'electoral_potential' =>	1671978, 'type' => 1, 'superior' => null],
		['name' => 'AGUA DE DIOS', 			'electoral_potential' =>	9407, 'type' => 2, 'superior' => 1],
		['name' => 'ALBAN', 				'electoral_potential' =>	4795, 'type' => 2, 'superior' => 1],
		['name' => 'ANAPOIMA', 				'electoral_potential' =>	10626, 'type' => 2, 'superior' => 1],
		['name' => 'ANOLAIMA', 				'electoral_potential' =>	11067, 'type' => 2, 'superior' => 1],
		['name' => 'APULO', 				'electoral_potential' =>	6717, 'type' => 2, 'superior' => 1],
		['name' => 'ARBELAEZ', 				'electoral_potential' =>	8300, 'type' => 2, 'superior' => 1],
		['name' => 'BELTRAN', 				'electoral_potential' =>	2003, 'type' => 2, 'superior' => 1],
		['name' => 'BITUIMA', 				'electoral_potential' =>	2844, 'type' => 2, 'superior' => 1],
		['name' => 'BOJACA', 				'electoral_potential' =>	5315, 'type' => 2, 'superior' => 1],
		['name' => 'CABRERA', 				'electoral_potential' =>	3282, 'type' => 2, 'superior' => 1],
		['name' => 'CACHIPAY', 				'electoral_potential' =>	8509, 'type' => 2, 'superior' => 1],
		['name' => 'CAJICA', 				'electoral_potential' =>	34539, 'type' => 2, 'superior' => 1],
		['name' => 'CAPARRAPI', 			'electoral_potential' =>	10272, 'type' => 2, 'superior' => 1],
		['name' => 'CAQUEZA', 				'electoral_potential' =>	14097, 'type' => 2, 'superior' => 1],
		['name' => 'CARMEN DE CARUPA', 		'electoral_potential' =>	6025, 'type' => 2, 'superior' => 1],
		['name' => 'CHAGUANI', 				'electoral_potential' =>	3725, 'type' => 2, 'superior' => 1],
		['name' => 'CHIA', 					'electoral_potential' =>	77779, 'type' => 2, 'superior' => 1],
		['name' => 'CHIPAQUE', 				'electoral_potential' =>	6993, 'type' => 2, 'superior' => 1],
		['name' => 'CHOACHI', 				'electoral_potential' =>	11062, 'type' => 2, 'superior' => 1],
		['name' => 'CHOCONTA', 				'electoral_potential' =>	13526, 'type' => 2, 'superior' => 1],
		['name' => 'COGUA', 				'electoral_potential' =>	12219, 'type' => 2, 'superior' => 1],
		['name' => 'COTA', 					'electoral_potential' =>	20752, 'type' => 2, 'superior' => 1],
		['name' => 'CUCUNUBA', 				'electoral_potential' =>	4530, 'type' => 2, 'superior' => 1],
		['name' => 'EL COLEGIO', 			'electoral_potential' =>	18346, 'type' => 2, 'superior' => 1],
		['name' => 'EL PEÑON', 				'electoral_potential' =>	4283, 'type' => 2, 'superior' => 1],
		['name' => 'EL ROSAL', 				'electoral_potential' =>	12280, 'type' => 2, 'superior' => 1],
		['name' => 'FACATATIVA', 			'electoral_potential' =>	80720, 'type' => 2, 'superior' => 1],
		['name' => 'FOMEQUE', 				'electoral_potential' =>	9188, 'type' => 2, 'superior' => 1],
		['name' => 'FOSCA', 				'electoral_potential' =>	5353, 'type' => 2, 'superior' => 1],
		['name' => 'FUNZA', 				'electoral_potential' =>	55981, 'type' => 2, 'superior' => 1],
		['name' => 'FUQUENE', 				'electoral_potential' =>	3690, 'type' => 2, 'superior' => 1],
		['name' => 'FUSAGASUGA', 			'electoral_potential' =>	91223, 'type' => 2, 'superior' => 1],
		['name' => 'GACHALA', 				'electoral_potential' =>	5076, 'type' => 2, 'superior' => 1],
		['name' => 'GACHANCIPA', 			'electoral_potential' =>	8519, 'type' => 2, 'superior' => 1],
		['name' => 'GACHETA', 				'electoral_potential' =>	9198, 'type' => 2, 'superior' => 1],
		['name' => 'GAMA', 					'electoral_potential' =>	3045, 'type' => 2, 'superior' => 1],
		['name' => 'GIRARDOT', 				'electoral_potential' =>	79200, 'type' => 2, 'superior' => 1],
		['name' => 'GRANADA', 				'electoral_potential' =>	5442, 'type' => 2, 'superior' => 1],
		['name' => 'GUACHETA', 				'electoral_potential' =>	8306, 'type' => 2, 'superior' => 1],
		['name' => 'GUADUAS', 				'electoral_potential' =>	21444, 'type' => 2, 'superior' => 1],
		['name' => 'GUASCA', 				'electoral_potential' =>	9617, 'type' => 2, 'superior' => 1],
		['name' => 'GUATAQUI', 				'electoral_potential' =>	2086, 'type' => 2, 'superior' => 1],
		['name' => 'GUATAVITA', 			'electoral_potential' =>	4747, 'type' => 2, 'superior' => 1],
		['name' => 'GUAYABAL DE SIQUIMA', 	'electoral_potential' =>	3524, 'type' => 2, 'superior' => 1],
		['name' => 'GUAYABETAL', 			'electoral_potential' =>	4285, 'type' => 2, 'superior' => 1],
		['name' => 'GUTIERREZ', 			'electoral_potential' =>	2631, 'type' => 2, 'superior' => 1],
		['name' => 'JERUSALEN', 			'electoral_potential' =>	2709, 'type' => 2, 'superior' => 1],
		['name' => 'JUNIN', 				'electoral_potential' =>	5483, 'type' => 2, 'superior' => 1],
		['name' => 'LA CALERA', 			'electoral_potential' =>	19108, 'type' => 2, 'superior' => 1],
		['name' => 'LA MESA', 				'electoral_potential' =>	22404, 'type' => 2, 'superior' => 1],
		['name' => 'LA PALMA', 				'electoral_potential' =>	8665, 'type' => 2, 'superior' => 1],
		['name' => 'LA PEÑA', 				'electoral_potential' => 	5503, 'type' => 2, 'superior' => 1],
		['name' => 'LA VEGA', 				'electoral_potential' =>	11652, 'type' => 2, 'superior' => 1],
		['name' => 'LENGUAZAQUE', 			'electoral_potential' =>	6606, 'type' => 2, 'superior' => 1],
		['name' => 'MACHETA', 				'electoral_potential' =>	6157, 'type' => 2, 'superior' => 1],
		['name' => 'MADRID', 				'electoral_potential' =>	49707, 'type' => 2, 'superior' => 1],
		['name' => 'MANTA', 				'electoral_potential' =>	4020, 'type' => 2, 'superior' => 1],
		['name' => 'MEDINA', 				'electoral_potential' =>	6728, 'type' => 2, 'superior' => 1],
		['name' => 'MOSQUERA', 				'electoral_potential' =>	51230, 'type' => 2, 'superior' => 1],
		['name' => 'NARIÑO', 				'electoral_potential' =>	2463, 'type' => 2, 'superior' => 1],
		['name' => 'NEMOCON', 				'electoral_potential' =>	8334, 'type' => 2, 'superior' => 1],
		['name' => 'NILO', 					'electoral_potential' =>	6149, 'type' => 2, 'superior' => 1],
		['name' => 'NIMAIMA', 				'electoral_potential' =>	3071, 'type' => 2, 'superior' => 1],
		['name' => 'NOCAIMA', 				'electoral_potential' =>	5135, 'type' => 2, 'superior' => 1],
		['name' => 'PACHO', 				'electoral_potential' =>	19875, 'type' => 2, 'superior' => 1],
		['name' => 'PAIME', 				'electoral_potential' =>	4433, 'type' => 2, 'superior' => 1],
		['name' => 'PANDI', 				'electoral_potential' =>	4012, 'type' => 2, 'superior' => 1],
		['name' => 'PARATEBUENO (LA NAGU', 	'electoral_potential' =>	6905, 'type' => 2, 'superior' => 1],
		['name' => 'PASCA', 				'electoral_potential' =>	7051, 'type' => 2, 'superior' => 1],
		['name' => 'PUERTO SALGAR', 		'electoral_potential' =>	13044, 'type' => 2, 'superior' => 1],
		['name' => 'PULI', 					'electoral_potential' =>	2817, 'type' => 2, 'superior' => 1],
		['name' => 'QUEBRADANEGRA', 		'electoral_potential' =>	3891, 'type' => 2, 'superior' => 1],
		['name' => 'QUETAME', 				'electoral_potential' =>	5261, 'type' => 2, 'superior' => 1],
		['name' => 'QUIPILE', 				'electoral_potential' =>	6084, 'type' => 2, 'superior' => 1],
		['name' => 'RICAURTE', 				'electoral_potential' =>	9961, 'type' => 2, 'superior' => 1],
		['name' => 'SAN ANTONIO DEL TEQU', 	'electoral_potential' =>	8190, 'type' => 2, 'superior' => 1],
		['name' => 'SAN BERNARDO', 			'electoral_potential' =>	7614, 'type' => 2, 'superior' => 1],
		['name' => 'SAN CAYETANO', 			'electoral_potential' =>	4348, 'type' => 2, 'superior' => 1],
		['name' => 'SAN FRANCISCO', 		'electoral_potential' =>	7842, 'type' => 2, 'superior' => 1],
		['name' => 'SAN JUAN DE RIOSECO', 	'electoral_potential' =>	8876, 'type' => 2, 'superior' => 1],
		['name' => 'SASAIMA', 				'electoral_potential' =>	8417, 'type' => 2, 'superior' => 1],
		['name' => 'SESQUILE', 				'electoral_potential' =>	7304, 'type' => 2, 'superior' => 1],
		['name' => 'SIBATE', 				'electoral_potential' =>	22986, 'type' => 2, 'superior' => 1],
		['name' => 'SILVANIA', 				'electoral_potential' =>	16048, 'type' => 2, 'superior' => 1],
		['name' => 'SIMIJACA', 				'electoral_potential' =>	8220, 'type' => 2, 'superior' => 1],
		['name' => 'SOACHA', 				'electoral_potential' =>	190969, 'type' => 2, 'superior' => 1],
		['name' => 'SOPO', 					'electoral_potential' =>	14970, 'type' => 2, 'superior' => 1],
		['name' => 'SUBACHOQUE', 			'electoral_potential' =>	10630, 'type' => 2, 'superior' => 1],
		['name' => 'SUESCA', 				'electoral_potential' =>	9435, 'type' => 2, 'superior' => 1],
		['name' => 'SUPATA', 				'electoral_potential' =>	4176, 'type' => 2, 'superior' => 1],
		['name' => 'SUSA', 					'electoral_potential' =>	5052, 'type' => 2, 'superior' => 1],
		['name' => 'SUTATAUSA', 			'electoral_potential' =>	3679, 'type' => 2, 'superior' => 1],
		['name' => 'TABIO', 				'electoral_potential' =>	13814, 'type' => 2, 'superior' => 1],
		['name' => 'TAUSA', 				'electoral_potential' =>	5527, 'type' => 2, 'superior' => 1],
		['name' => 'TENA', 					'electoral_potential' =>	6050, 'type' => 2, 'superior' => 1],
		['name' => 'TENJO', 				'electoral_potential' =>	13067, 'type' => 2, 'superior' => 1],
		['name' => 'TIBACUY', 				'electoral_potential' =>	3638, 'type' => 2, 'superior' => 1],
		['name' => 'TIBIRITA', 				'electoral_potential' =>	3033, 'type' => 2, 'superior' => 1],
		['name' => 'TOCAIMA', 				'electoral_potential' =>	12777, 'type' => 2, 'superior' => 1],
		['name' => 'TOCANCIPA', 			'electoral_potential' =>	21852, 'type' => 2, 'superior' => 1],
		['name' => 'TOPAIPI', 				'electoral_potential' =>	4084, 'type' => 2, 'superior' => 1],
		['name' => 'UBALA', 				'electoral_potential' =>	8421, 'type' => 2, 'superior' => 1],
		['name' => 'UBAQUE', 				'electoral_potential' =>	5478, 'type' => 2, 'superior' => 1],
		['name' => 'UBATE', 				'electoral_potential' =>	28883, 'type' => 2, 'superior' => 1],
		['name' => 'UNE', 					'electoral_potential' =>	6049, 'type' => 2, 'superior' => 1],
		['name' => 'UTICA', 				'electoral_potential' =>	4587, 'type' => 2, 'superior' => 1],
		['name' => 'VENECIA', 				'electoral_potential' =>	3438, 'type' => 2, 'superior' => 1],
		['name' => 'VERGARA', 				'electoral_potential' =>	7002, 'type' => 2, 'superior' => 1],
		['name' => 'VIANI', 				'electoral_potential' =>	3810, 'type' => 2, 'superior' => 1],
		['name' => 'VILLAGOMEZ', 			'electoral_potential' =>	1895, 'type' => 2, 'superior' => 1],
		['name' => 'VILLAPINZON', 			'electoral_potential' =>	12299, 'type' => 2, 'superior' => 1],
		['name' => 'VILLETA', 				'electoral_potential' =>	21096, 'type' => 2, 'superior' => 1],
		['name' => 'VIOTA', 				'electoral_potential' =>	9915, 'type' => 2, 'superior' => 1],
		['name' => 'YACOPI', 				'electoral_potential' =>	11480, 'type' => 2, 'superior' => 1],
		['name' => 'ZIPACON', 				'electoral_potential' =>	3821, 'type' => 2, 'superior' => 1],
		['name' => 'ZIPAQUIRA', 			'electoral_potential' =>	7618, 'type' => 2, 'superior' => 1]
	];

    public function run()
    {
        $locations = self::$locations;

        foreach ($locations as $location) {         
            Location::create([
                'name'      			=> strtolower($location['name']),
                'type_id'   			=> $location['type'],
                'superior'  			=> $location['superior'],
                'electoral_potential'   => $location['electoral_potential'],
                'created_at'    		=> new DateTime,
                'updated_at'    		=> new DateTime 
            ]);                
        }
    }
}

?>

